import { lazy } from 'react';

export const templateRoutes = [
  {
    path: '/Accounts/account_adjustments',
    label: 'Accounts/account_adjustments.php',
    sourcePath: 'templates/Accounts/account_adjustments.php',
    Component: lazy(() => import('./pages/Accounts/account_adjustments')),
  },
  {
    path: '/Accounts/account_view',
    label: 'Accounts/account_view.php',
    sourcePath: 'templates/Accounts/account_view.php',
    Component: lazy(() => import('./pages/Accounts/account_view')),
  },
  {
    path: '/Accounts/fy_bookeeping',
    label: 'Accounts/fy_bookeeping.php',
    sourcePath: 'templates/Accounts/fy_bookeeping.php',
    Component: lazy(() => import('./pages/Accounts/fy_bookeeping')),
  },
  {
    path: '/Accounts/index',
    label: 'Accounts/index.php',
    sourcePath: 'templates/Accounts/index.php',
    Component: lazy(() => import('./pages/Accounts/index')),
  },
  {
    path: '/Accounts/manage_accounts',
    label: 'Accounts/manage_accounts.php',
    sourcePath: 'templates/Accounts/manage_accounts.php',
    Component: lazy(() => import('./pages/Accounts/manage_accounts')),
  },
  {
    path: '/Accounts/required_actions',
    label: 'Accounts/required_actions.php',
    sourcePath: 'templates/Accounts/required_actions.php',
    Component: lazy(() => import('./pages/Accounts/required_actions')),
  },
  {
    path: '/Billings/analytics',
    label: 'Billings/analytics.php',
    sourcePath: 'templates/Billings/analytics.php',
    Component: lazy(() => import('./pages/Billings/analytics')),
  },
  {
    path: '/Billings/analytics_copy',
    label: 'Billings/analytics_copy.php',
    sourcePath: 'templates/Billings/analytics_copy.php',
    Component: lazy(() => import('./pages/Billings/analytics_copy')),
  },
  {
    path: '/Billings/billing_report',
    label: 'Billings/billing_report.php',
    sourcePath: 'templates/Billings/billing_report.php',
    Component: lazy(() => import('./pages/Billings/billing_report')),
  },
  {
    path: '/Billings/export_data_to_pdf',
    label: 'Billings/export_data_to_pdf.php',
    sourcePath: 'templates/Billings/export_data_to_pdf.php',
    Component: lazy(() => import('./pages/Billings/export_data_to_pdf')),
  },
  {
    path: '/Billings/index',
    label: 'Billings/index.php',
    sourcePath: 'templates/Billings/index.php',
    Component: lazy(() => import('./pages/Billings/index')),
  },
  {
    path: '/Billings/index_2021_08_31',
    label: 'Billings/index_2021_08_31.php',
    sourcePath: 'templates/Billings/index_2021_08_31.php',
    Component: lazy(() => import('./pages/Billings/index_2021_08_31')),
  },
  {
    path: '/Billings/indexed',
    label: 'Billings/indexed.php',
    sourcePath: 'templates/Billings/indexed.php',
    Component: lazy(() => import('./pages/Billings/indexed')),
  },
  {
    path: '/Billings/insurance_billing_report',
    label: 'Billings/insurance_billing_report.php',
    sourcePath: 'templates/Billings/insurance_billing_report.php',
    Component: lazy(() => import('./pages/Billings/insurance_billing_report')),
  },
  {
    path: '/Billings/invoice_payments',
    label: 'Billings/invoice_payments.php',
    sourcePath: 'templates/Billings/invoice_payments.php',
    Component: lazy(() => import('./pages/Billings/invoice_payments')),
  },
  {
    path: '/Billings/new_billing_report',
    label: 'Billings/new_billing_report.php',
    sourcePath: 'templates/Billings/new_billing_report.php',
    Component: lazy(() => import('./pages/Billings/new_billing_report')),
  },
  {
    path: '/Billings/patient_outstanding_bills',
    label: 'Billings/patient_outstanding_bills.php',
    sourcePath: 'templates/Billings/patient_outstanding_bills.php',
    Component: lazy(() => import('./pages/Billings/patient_outstanding_bills')),
  },
  {
    path: '/Billings/pdf/view_invoice',
    label: 'Billings/pdf/view_invoice.php',
    sourcePath: 'templates/Billings/pdf/view_invoice.php',
    Component: lazy(() => import('./pages/Billings/pdf/view_invoice')),
  },
  {
    path: '/Billings/receipt',
    label: 'Billings/receipt.php',
    sourcePath: 'templates/Billings/receipt.php',
    Component: lazy(() => import('./pages/Billings/receipt')),
  },
  {
    path: '/Billings/reconcile',
    label: 'Billings/reconcile.php',
    sourcePath: 'templates/Billings/reconcile.php',
    Component: lazy(() => import('./pages/Billings/reconcile')),
  },
  {
    path: '/Billings/sales_reversals',
    label: 'Billings/sales_reversals.php',
    sourcePath: 'templates/Billings/sales_reversals.php',
    Component: lazy(() => import('./pages/Billings/sales_reversals')),
  },
  {
    path: '/Billings/session_vouchers',
    label: 'Billings/session_vouchers.php',
    sourcePath: 'templates/Billings/session_vouchers.php',
    Component: lazy(() => import('./pages/Billings/session_vouchers')),
  },
  {
    path: '/Billings/super_bill',
    label: 'Billings/super_bill.php',
    sourcePath: 'templates/Billings/super_bill.php',
    Component: lazy(() => import('./pages/Billings/super_bill')),
  },
  {
    path: '/Billings/view_invoice',
    label: 'Billings/view_invoice.php',
    sourcePath: 'templates/Billings/view_invoice.php',
    Component: lazy(() => import('./pages/Billings/view_invoice')),
  },
  {
    path: '/Book/index',
    label: 'Book/index.php',
    sourcePath: 'templates/Book/index.php',
    Component: lazy(() => import('./pages/Book/index')),
  },
  {
    path: '/Book/index_copy',
    label: 'Book/index_copy.php',
    sourcePath: 'templates/Book/index_copy.php',
    Component: lazy(() => import('./pages/Book/index_copy')),
  },
  {
    path: '/Book/index_copy_abu',
    label: 'Book/index_copy_abu.php',
    sourcePath: 'templates/Book/index_copy_abu.php',
    Component: lazy(() => import('./pages/Book/index_copy_abu')),
  },
  {
    path: '/Book/manage_appointments',
    label: 'Book/manage_appointments.php',
    sourcePath: 'templates/Book/manage_appointments.php',
    Component: lazy(() => import('./pages/Book/manage_appointments')),
  },
  {
    path: '/Budgeting/index',
    label: 'Budgeting/index.php',
    sourcePath: 'templates/Budgeting/index.php',
    Component: lazy(() => import('./pages/Budgeting/index')),
  },
  {
    path: '/Cash/cash_records',
    label: 'Cash/cash_records.php',
    sourcePath: 'templates/Cash/cash_records.php',
    Component: lazy(() => import('./pages/Cash/cash_records')),
  },
  {
    path: '/Cash/cash_records_copy',
    label: 'Cash/cash_records_copy.php',
    sourcePath: 'templates/Cash/cash_records_copy.php',
    Component: lazy(() => import('./pages/Cash/cash_records_copy')),
  },
  {
    path: '/Cash/cash_records_old',
    label: 'Cash/cash_records_old.php',
    sourcePath: 'templates/Cash/cash_records_old.php',
    Component: lazy(() => import('./pages/Cash/cash_records_old')),
  },
  {
    path: '/Cash/cash_settlement',
    label: 'Cash/cash_settlement.php',
    sourcePath: 'templates/Cash/cash_settlement.php',
    Component: lazy(() => import('./pages/Cash/cash_settlement')),
  },
  {
    path: '/Cash/cashier_sales',
    label: 'Cash/cashier_sales.php',
    sourcePath: 'templates/Cash/cashier_sales.php',
    Component: lazy(() => import('./pages/Cash/cashier_sales')),
  },
  {
    path: '/Cash/index',
    label: 'Cash/index.php',
    sourcePath: 'templates/Cash/index.php',
    Component: lazy(() => import('./pages/Cash/index')),
  },
  {
    path: '/Cash/print_cash_records',
    label: 'Cash/print_cash_records.php',
    sourcePath: 'templates/Cash/print_cash_records.php',
    Component: lazy(() => import('./pages/Cash/print_cash_records')),
  },
  {
    path: '/Cash/print_sales_report',
    label: 'Cash/print_sales_report.php',
    sourcePath: 'templates/Cash/print_sales_report.php',
    Component: lazy(() => import('./pages/Cash/print_sales_report')),
  },
  {
    path: '/Cash/refunds',
    label: 'Cash/refunds.php',
    sourcePath: 'templates/Cash/refunds.php',
    Component: lazy(() => import('./pages/Cash/refunds')),
  },
  {
    path: '/Cash/submit_sales',
    label: 'Cash/submit_sales.php',
    sourcePath: 'templates/Cash/submit_sales.php',
    Component: lazy(() => import('./pages/Cash/submit_sales')),
  },
  {
    path: '/Cash/view_sales_report',
    label: 'Cash/view_sales_report.php',
    sourcePath: 'templates/Cash/view_sales_report.php',
    Component: lazy(() => import('./pages/Cash/view_sales_report')),
  },
  {
    path: '/CashBook/edit_consultation_price_credit',
    label: 'CashBook/edit_consultation_price_credit.php',
    sourcePath: 'templates/CashBook/edit_consultation_price_credit.php',
    Component: lazy(() => import('./pages/CashBook/edit_consultation_price_credit')),
  },
  {
    path: '/CashBook/edit_drug_price',
    label: 'CashBook/edit_drug_price.php',
    sourcePath: 'templates/CashBook/edit_drug_price.php',
    Component: lazy(() => import('./pages/CashBook/edit_drug_price')),
  },
  {
    path: '/CashBook/edit_drug_price_credit',
    label: 'CashBook/edit_drug_price_credit.php',
    sourcePath: 'templates/CashBook/edit_drug_price_credit.php',
    Component: lazy(() => import('./pages/CashBook/edit_drug_price_credit')),
  },
  {
    path: '/CashBook/edit_lab_test_price',
    label: 'CashBook/edit_lab_test_price.php',
    sourcePath: 'templates/CashBook/edit_lab_test_price.php',
    Component: lazy(() => import('./pages/CashBook/edit_lab_test_price')),
  },
  {
    path: '/CashBook/edit_lab_test_price_credit',
    label: 'CashBook/edit_lab_test_price_credit.php',
    sourcePath: 'templates/CashBook/edit_lab_test_price_credit.php',
    Component: lazy(() => import('./pages/CashBook/edit_lab_test_price_credit')),
  },
  {
    path: '/CashBook/edit_procedure_price_credit',
    label: 'CashBook/edit_procedure_price_credit.php',
    sourcePath: 'templates/CashBook/edit_procedure_price_credit.php',
    Component: lazy(() => import('./pages/CashBook/edit_procedure_price_credit')),
  },
  {
    path: '/CashBook/edit_procedure_stocks_price_credit',
    label: 'CashBook/edit_procedure_stocks_price_credit.php',
    sourcePath: 'templates/CashBook/edit_procedure_stocks_price_credit.php',
    Component: lazy(() => import('./pages/CashBook/edit_procedure_stocks_price_credit')),
  },
  {
    path: '/CashBook/edit_radiology_price_credit',
    label: 'CashBook/edit_radiology_price_credit.php',
    sourcePath: 'templates/CashBook/edit_radiology_price_credit.php',
    Component: lazy(() => import('./pages/CashBook/edit_radiology_price_credit')),
  },
  {
    path: '/CashBook/edit_service_stock_price',
    label: 'CashBook/edit_service_stock_price.php',
    sourcePath: 'templates/CashBook/edit_service_stock_price.php',
    Component: lazy(() => import('./pages/CashBook/edit_service_stock_price')),
  },
  {
    path: '/CashBook/edit_service_stock_price_credit',
    label: 'CashBook/edit_service_stock_price_credit.php',
    sourcePath: 'templates/CashBook/edit_service_stock_price_credit.php',
    Component: lazy(() => import('./pages/CashBook/edit_service_stock_price_credit')),
  },
  {
    path: '/CashBook/edit_ward_price_credit',
    label: 'CashBook/edit_ward_price_credit.php',
    sourcePath: 'templates/CashBook/edit_ward_price_credit.php',
    Component: lazy(() => import('./pages/CashBook/edit_ward_price_credit')),
  },
  {
    path: '/CashBook/index',
    label: 'CashBook/index.php',
    sourcePath: 'templates/CashBook/index.php',
    Component: lazy(() => import('./pages/CashBook/index')),
  },
  {
    path: '/CashFlow/index',
    label: 'CashFlow/index.php',
    sourcePath: 'templates/CashFlow/index.php',
    Component: lazy(() => import('./pages/CashFlow/index')),
  },
  {
    path: '/Concierge/birthday',
    label: 'Concierge/birthday.php',
    sourcePath: 'templates/Concierge/birthday.php',
    Component: lazy(() => import('./pages/Concierge/birthday')),
  },
  {
    path: '/Concierge/index',
    label: 'Concierge/index.php',
    sourcePath: 'templates/Concierge/index.php',
    Component: lazy(() => import('./pages/Concierge/index')),
  },
  {
    path: '/CreditClaims/analytics',
    label: 'CreditClaims/analytics.php',
    sourcePath: 'templates/CreditClaims/analytics.php',
    Component: lazy(() => import('./pages/CreditClaims/analytics')),
  },
  {
    path: '/CreditClaims/claim_pdf',
    label: 'CreditClaims/claim_pdf.php',
    sourcePath: 'templates/CreditClaims/claim_pdf.php',
    Component: lazy(() => import('./pages/CreditClaims/claim_pdf')),
  },
  {
    path: '/CreditClaims/claim_reconciliation',
    label: 'CreditClaims/claim_reconciliation.php',
    sourcePath: 'templates/CreditClaims/claim_reconciliation.php',
    Component: lazy(() => import('./pages/CreditClaims/claim_reconciliation')),
  },
  {
    path: '/CreditClaims/completed_invoices',
    label: 'CreditClaims/completed_invoices.php',
    sourcePath: 'templates/CreditClaims/completed_invoices.php',
    Component: lazy(() => import('./pages/CreditClaims/completed_invoices')),
  },
  {
    path: '/CreditClaims/denied_claims',
    label: 'CreditClaims/denied_claims.php',
    sourcePath: 'templates/CreditClaims/denied_claims.php',
    Component: lazy(() => import('./pages/CreditClaims/denied_claims')),
  },
  {
    path: '/CreditClaims/diag_backup',
    label: 'CreditClaims/diag_backup.php',
    sourcePath: 'templates/CreditClaims/diag_backup.php',
    Component: lazy(() => import('./pages/CreditClaims/diag_backup')),
  },
  {
    path: '/CreditClaims/export_data_to_pdf',
    label: 'CreditClaims/export_data_to_pdf.php',
    sourcePath: 'templates/CreditClaims/export_data_to_pdf.php',
    Component: lazy(() => import('./pages/CreditClaims/export_data_to_pdf')),
  },
  {
    path: '/CreditClaims/flagged_and_submitted_claims',
    label: 'CreditClaims/flagged_and_submitted_claims.php',
    sourcePath: 'templates/CreditClaims/flagged_and_submitted_claims.php',
    Component: lazy(() => import('./pages/CreditClaims/flagged_and_submitted_claims')),
  },
  {
    path: '/CreditClaims/index',
    label: 'CreditClaims/index.php',
    sourcePath: 'templates/CreditClaims/index.php',
    Component: lazy(() => import('./pages/CreditClaims/index')),
  },
  {
    path: '/CreditClaims/manage_scrubber',
    label: 'CreditClaims/manage_scrubber.php',
    sourcePath: 'templates/CreditClaims/manage_scrubber.php',
    Component: lazy(() => import('./pages/CreditClaims/manage_scrubber')),
  },
  {
    path: '/CreditClaims/paid_claims',
    label: 'CreditClaims/paid_claims.php',
    sourcePath: 'templates/CreditClaims/paid_claims.php',
    Component: lazy(() => import('./pages/CreditClaims/paid_claims')),
  },
  {
    path: '/CreditClaims/pdf/claim_pdf_backup',
    label: 'CreditClaims/pdf/claim_pdf_backup.php',
    sourcePath: 'templates/CreditClaims/pdf/claim_pdf_backup.php',
    Component: lazy(() => import('./pages/CreditClaims/pdf/claim_pdf_backup')),
  },
  {
    path: '/CreditClaims/submit_claim',
    label: 'CreditClaims/submit_claim.php',
    sourcePath: 'templates/CreditClaims/submit_claim.php',
    Component: lazy(() => import('./pages/CreditClaims/submit_claim')),
  },
  {
    path: '/CreditClaims/summary',
    label: 'CreditClaims/summary.php',
    sourcePath: 'templates/CreditClaims/summary.php',
    Component: lazy(() => import('./pages/CreditClaims/summary')),
  },
  {
    path: '/CreditClaims/view_claim_details',
    label: 'CreditClaims/view_claim_details.php',
    sourcePath: 'templates/CreditClaims/view_claim_details.php',
    Component: lazy(() => import('./pages/CreditClaims/view_claim_details')),
  },
  {
    path: '/CreditClaims/view_claim_details_backup',
    label: 'CreditClaims/view_claim_details_backup.php',
    sourcePath: 'templates/CreditClaims/view_claim_details_backup.php',
    Component: lazy(() => import('./pages/CreditClaims/view_claim_details_backup')),
  },
  {
    path: '/CreditClaims/view_claim_details_inpatient',
    label: 'CreditClaims/view_claim_details_inpatient.php',
    sourcePath: 'templates/CreditClaims/view_claim_details_inpatient.php',
    Component: lazy(() => import('./pages/CreditClaims/view_claim_details_inpatient')),
  },
  {
    path: '/Departments/add_department',
    label: 'Departments/add_department.php',
    sourcePath: 'templates/Departments/add_department.php',
    Component: lazy(() => import('./pages/Departments/add_department')),
  },
  {
    path: '/Departments/edit_department',
    label: 'Departments/edit_department.php',
    sourcePath: 'templates/Departments/edit_department.php',
    Component: lazy(() => import('./pages/Departments/edit_department')),
  },
  {
    path: '/Departments/view_departments',
    label: 'Departments/view_departments.php',
    sourcePath: 'templates/Departments/view_departments.php',
    Component: lazy(() => import('./pages/Departments/view_departments')),
  },
  {
    path: '/DrugConsumptionReport/index',
    label: 'DrugConsumptionReport/index.php',
    sourcePath: 'templates/DrugConsumptionReport/index.php',
    Component: lazy(() => import('./pages/DrugConsumptionReport/index')),
  },
  {
    path: '/email/html/birthday',
    label: 'email/html/birthday.php',
    sourcePath: 'templates/email/html/birthday.php',
    Component: lazy(() => import('./pages/email/html/birthday')),
  },
  {
    path: '/email/html/default',
    label: 'email/html/default.php',
    sourcePath: 'templates/email/html/default.php',
    Component: lazy(() => import('./pages/email/html/default')),
  },
  {
    path: '/email/html/invoice_template',
    label: 'email/html/invoice_template.php',
    sourcePath: 'templates/email/html/invoice_template.php',
    Component: lazy(() => import('./pages/email/html/invoice_template')),
  },
  {
    path: '/email/html/lab',
    label: 'email/html/lab.php',
    sourcePath: 'templates/email/html/lab.php',
    Component: lazy(() => import('./pages/email/html/lab')),
  },
  {
    path: '/email/html/patient_portal_view',
    label: 'email/html/patient_portal_view.php',
    sourcePath: 'templates/email/html/patient_portal_view.php',
    Component: lazy(() => import('./pages/email/html/patient_portal_view')),
  },
  {
    path: '/email/html/receipt',
    label: 'email/html/receipt.php',
    sourcePath: 'templates/email/html/receipt.php',
    Component: lazy(() => import('./pages/email/html/receipt')),
  },
  {
    path: '/email/text/default',
    label: 'email/text/default.php',
    sourcePath: 'templates/email/text/default.php',
    Component: lazy(() => import('./pages/email/text/default')),
  },
  {
    path: '/Error/error400',
    label: 'Error/error400.php',
    sourcePath: 'templates/Error/error400.php',
    Component: lazy(() => import('./pages/Error/error400')),
  },
  {
    path: '/Error/error400_bak',
    label: 'Error/error400_bak.php',
    sourcePath: 'templates/Error/error400_bak.php',
    Component: lazy(() => import('./pages/Error/error400_bak')),
  },
  {
    path: '/Error/error500',
    label: 'Error/error500.php',
    sourcePath: 'templates/Error/error500.php',
    Component: lazy(() => import('./pages/Error/error500')),
  },
  {
    path: '/Error/error500_bak',
    label: 'Error/error500_bak.php',
    sourcePath: 'templates/Error/error500_bak.php',
    Component: lazy(() => import('./pages/Error/error500_bak')),
  },
  {
    path: '/Expenses/approve_invoice_modal',
    label: 'Expenses/approve_invoice_modal.php',
    sourcePath: 'templates/Expenses/approve_invoice_modal.php',
    Component: lazy(() => import('./pages/Expenses/approve_invoice_modal')),
  },
  {
    path: '/Expenses/disable_pending_modal',
    label: 'Expenses/disable_pending_modal.php',
    sourcePath: 'templates/Expenses/disable_pending_modal.php',
    Component: lazy(() => import('./pages/Expenses/disable_pending_modal')),
  },
  {
    path: '/Expenses/disable_recurring_modal',
    label: 'Expenses/disable_recurring_modal.php',
    sourcePath: 'templates/Expenses/disable_recurring_modal.php',
    Component: lazy(() => import('./pages/Expenses/disable_recurring_modal')),
  },
  {
    path: '/Expenses/enable_pending_modal',
    label: 'Expenses/enable_pending_modal.php',
    sourcePath: 'templates/Expenses/enable_pending_modal.php',
    Component: lazy(() => import('./pages/Expenses/enable_pending_modal')),
  },
  {
    path: '/Expenses/enable_recurring_modal',
    label: 'Expenses/enable_recurring_modal.php',
    sourcePath: 'templates/Expenses/enable_recurring_modal.php',
    Component: lazy(() => import('./pages/Expenses/enable_recurring_modal')),
  },
  {
    path: '/Expenses/index',
    label: 'Expenses/index.php',
    sourcePath: 'templates/Expenses/index.php',
    Component: lazy(() => import('./pages/Expenses/index')),
  },
  {
    path: '/Expenses/pending_amount_modal',
    label: 'Expenses/pending_amount_modal.php',
    sourcePath: 'templates/Expenses/pending_amount_modal.php',
    Component: lazy(() => import('./pages/Expenses/pending_amount_modal')),
  },
  {
    path: '/Expenses/pending_modal',
    label: 'Expenses/pending_modal.php',
    sourcePath: 'templates/Expenses/pending_modal.php',
    Component: lazy(() => import('./pages/Expenses/pending_modal')),
  },
  {
    path: '/Expenses/pending_record_modal',
    label: 'Expenses/pending_record_modal.php',
    sourcePath: 'templates/Expenses/pending_record_modal.php',
    Component: lazy(() => import('./pages/Expenses/pending_record_modal')),
  },
  {
    path: '/Expenses/recurring_amount_modal',
    label: 'Expenses/recurring_amount_modal.php',
    sourcePath: 'templates/Expenses/recurring_amount_modal.php',
    Component: lazy(() => import('./pages/Expenses/recurring_amount_modal')),
  },
  {
    path: '/Expenses/recurring_approve_invoice_modal',
    label: 'Expenses/recurring_approve_invoice_modal.php',
    sourcePath: 'templates/Expenses/recurring_approve_invoice_modal.php',
    Component: lazy(() => import('./pages/Expenses/recurring_approve_invoice_modal')),
  },
  {
    path: '/Expenses/recurring_modal',
    label: 'Expenses/recurring_modal.php',
    sourcePath: 'templates/Expenses/recurring_modal.php',
    Component: lazy(() => import('./pages/Expenses/recurring_modal')),
  },
  {
    path: '/Expenses/recurring_record_modal',
    label: 'Expenses/recurring_record_modal.php',
    sourcePath: 'templates/Expenses/recurring_record_modal.php',
    Component: lazy(() => import('./pages/Expenses/recurring_record_modal')),
  },
  {
    path: '/Expenses/writeoff_pending_modal',
    label: 'Expenses/writeoff_pending_modal.php',
    sourcePath: 'templates/Expenses/writeoff_pending_modal.php',
    Component: lazy(() => import('./pages/Expenses/writeoff_pending_modal')),
  },
  {
    path: '/Expenses/writeoff_recurring_modal',
    label: 'Expenses/writeoff_recurring_modal.php',
    sourcePath: 'templates/Expenses/writeoff_recurring_modal.php',
    Component: lazy(() => import('./pages/Expenses/writeoff_recurring_modal')),
  },
  {
    path: '/Followups/all',
    label: 'Followups/all.php',
    sourcePath: 'templates/Followups/all.php',
    Component: lazy(() => import('./pages/Followups/all')),
  },
  {
    path: '/Followups/edit_followups',
    label: 'Followups/edit_followups.php',
    sourcePath: 'templates/Followups/edit_followups.php',
    Component: lazy(() => import('./pages/Followups/edit_followups')),
  },
  {
    path: '/Followups/index',
    label: 'Followups/index.php',
    sourcePath: 'templates/Followups/index.php',
    Component: lazy(() => import('./pages/Followups/index')),
  },
  {
    path: '/Followups/report',
    label: 'Followups/report.php',
    sourcePath: 'templates/Followups/report.php',
    Component: lazy(() => import('./pages/Followups/report')),
  },
  {
    path: '/Followups/today',
    label: 'Followups/today.php',
    sourcePath: 'templates/Followups/today.php',
    Component: lazy(() => import('./pages/Followups/today')),
  },
  {
    path: '/Followups/view_followups',
    label: 'Followups/view_followups.php',
    sourcePath: 'templates/Followups/view_followups.php',
    Component: lazy(() => import('./pages/Followups/view_followups')),
  },
  {
    path: '/Home/index',
    label: 'Home/index.php',
    sourcePath: 'templates/Home/index.php',
    Component: lazy(() => import('./pages/Home/index')),
  },
  {
    path: '/Home/patient',
    label: 'Home/patient.php',
    sourcePath: 'templates/Home/patient.php',
    Component: lazy(() => import('./pages/Home/patient')),
  },
  {
    path: '/ImmunizationRequest/flagged_requests',
    label: 'ImmunizationRequest/flagged_requests.php',
    sourcePath: 'templates/ImmunizationRequest/flagged_requests.php',
    Component: lazy(() => import('./pages/ImmunizationRequest/flagged_requests')),
  },
  {
    path: '/ImmunizationRequest/followup_immunization_requests',
    label: 'ImmunizationRequest/followup_immunization_requests.php',
    sourcePath: 'templates/ImmunizationRequest/followup_immunization_requests.php',
    Component: lazy(() => import('./pages/ImmunizationRequest/followup_immunization_requests')),
  },
  {
    path: '/ImmunizationRequest/index',
    label: 'ImmunizationRequest/index.php',
    sourcePath: 'templates/ImmunizationRequest/index.php',
    Component: lazy(() => import('./pages/ImmunizationRequest/index')),
  },
  {
    path: '/ImmunizationRequest/manage_vaccines',
    label: 'ImmunizationRequest/manage_vaccines.php',
    sourcePath: 'templates/ImmunizationRequest/manage_vaccines.php',
    Component: lazy(() => import('./pages/ImmunizationRequest/manage_vaccines')),
  },
  {
    path: '/ImmunizationRequest/pdf/immunization_report',
    label: 'ImmunizationRequest/pdf/immunization_report.php',
    sourcePath: 'templates/ImmunizationRequest/pdf/immunization_report.php',
    Component: lazy(() => import('./pages/ImmunizationRequest/pdf/immunization_report')),
  },
  {
    path: '/ImmunizationRequest/reports',
    label: 'ImmunizationRequest/reports.php',
    sourcePath: 'templates/ImmunizationRequest/reports.php',
    Component: lazy(() => import('./pages/ImmunizationRequest/reports')),
  },
  {
    path: '/ImmunizationRequest/view_immunization_requests',
    label: 'ImmunizationRequest/view_immunization_requests.php',
    sourcePath: 'templates/ImmunizationRequest/view_immunization_requests.php',
    Component: lazy(() => import('./pages/ImmunizationRequest/view_immunization_requests')),
  },
  {
    path: '/Institutions/index',
    label: 'Institutions/index.php',
    sourcePath: 'templates/Institutions/index.php',
    Component: lazy(() => import('./pages/Institutions/index')),
  },
  {
    path: '/InsuranceProfilePolicies/add',
    label: 'InsuranceProfilePolicies/add.php',
    sourcePath: 'templates/InsuranceProfilePolicies/add.php',
    Component: lazy(() => import('./pages/InsuranceProfilePolicies/add')),
  },
  {
    path: '/InsuranceProfilePolicies/edit',
    label: 'InsuranceProfilePolicies/edit.php',
    sourcePath: 'templates/InsuranceProfilePolicies/edit.php',
    Component: lazy(() => import('./pages/InsuranceProfilePolicies/edit')),
  },
  {
    path: '/InsuranceProfilePolicies/index',
    label: 'InsuranceProfilePolicies/index.php',
    sourcePath: 'templates/InsuranceProfilePolicies/index.php',
    Component: lazy(() => import('./pages/InsuranceProfilePolicies/index')),
  },
  {
    path: '/InsuranceProfilePolicies/view',
    label: 'InsuranceProfilePolicies/view.php',
    sourcePath: 'templates/InsuranceProfilePolicies/view.php',
    Component: lazy(() => import('./pages/InsuranceProfilePolicies/view')),
  },
  {
    path: '/InsuranceProfiles/add',
    label: 'InsuranceProfiles/add.php',
    sourcePath: 'templates/InsuranceProfiles/add.php',
    Component: lazy(() => import('./pages/InsuranceProfiles/add')),
  },
  {
    path: '/InsuranceProfiles/edit',
    label: 'InsuranceProfiles/edit.php',
    sourcePath: 'templates/InsuranceProfiles/edit.php',
    Component: lazy(() => import('./pages/InsuranceProfiles/edit')),
  },
  {
    path: '/InsuranceProfiles/index',
    label: 'InsuranceProfiles/index.php',
    sourcePath: 'templates/InsuranceProfiles/index.php',
    Component: lazy(() => import('./pages/InsuranceProfiles/index')),
  },
  {
    path: '/InsuranceProfiles/view',
    label: 'InsuranceProfiles/view.php',
    sourcePath: 'templates/InsuranceProfiles/view.php',
    Component: lazy(() => import('./pages/InsuranceProfiles/view')),
  },
  {
    path: '/Inventory/add_medicine',
    label: 'Inventory/add_medicine.php',
    sourcePath: 'templates/Inventory/add_medicine.php',
    Component: lazy(() => import('./pages/Inventory/add_medicine')),
  },
  {
    path: '/Inventory/assess_transfer',
    label: 'Inventory/assess_transfer.php',
    sourcePath: 'templates/Inventory/assess_transfer.php',
    Component: lazy(() => import('./pages/Inventory/assess_transfer')),
  },
  {
    path: '/Inventory/baskets',
    label: 'Inventory/baskets.php',
    sourcePath: 'templates/Inventory/baskets.php',
    Component: lazy(() => import('./pages/Inventory/baskets')),
  },
  {
    path: '/Inventory/blood_bank',
    label: 'Inventory/blood_bank.php',
    sourcePath: 'templates/Inventory/blood_bank.php',
    Component: lazy(() => import('./pages/Inventory/blood_bank')),
  },
  {
    path: '/Inventory/categories',
    label: 'Inventory/categories.php',
    sourcePath: 'templates/Inventory/categories.php',
    Component: lazy(() => import('./pages/Inventory/categories')),
  },
  {
    path: '/Inventory/consumables',
    label: 'Inventory/consumables.php',
    sourcePath: 'templates/Inventory/consumables.php',
    Component: lazy(() => import('./pages/Inventory/consumables')),
  },
  {
    path: '/Inventory/count',
    label: 'Inventory/count.php',
    sourcePath: 'templates/Inventory/count.php',
    Component: lazy(() => import('./pages/Inventory/count')),
  },
  {
    path: '/Inventory/department_store',
    label: 'Inventory/department_store.php',
    sourcePath: 'templates/Inventory/department_store.php',
    Component: lazy(() => import('./pages/Inventory/department_store')),
  },
  {
    path: '/Inventory/drug_consumption',
    label: 'Inventory/drug_consumption.php',
    sourcePath: 'templates/Inventory/drug_consumption.php',
    Component: lazy(() => import('./pages/Inventory/drug_consumption')),
  },
  {
    path: '/Inventory/drug_filtered',
    label: 'Inventory/drug_filtered.php',
    sourcePath: 'templates/Inventory/drug_filtered.php',
    Component: lazy(() => import('./pages/Inventory/drug_filtered')),
  },
  {
    path: '/Inventory/drug_stock_filtered',
    label: 'Inventory/drug_stock_filtered.php',
    sourcePath: 'templates/Inventory/drug_stock_filtered.php',
    Component: lazy(() => import('./pages/Inventory/drug_stock_filtered')),
  },
  {
    path: '/Inventory/drugs',
    label: 'Inventory/drugs.php',
    sourcePath: 'templates/Inventory/drugs.php',
    Component: lazy(() => import('./pages/Inventory/drugs')),
  },
  {
    path: '/Inventory/edit_item_modal',
    label: 'Inventory/edit_item_modal.php',
    sourcePath: 'templates/Inventory/edit_item_modal.php',
    Component: lazy(() => import('./pages/Inventory/edit_item_modal')),
  },
  {
    path: '/Inventory/forcasting',
    label: 'Inventory/forcasting.php',
    sourcePath: 'templates/Inventory/forcasting.php',
    Component: lazy(() => import('./pages/Inventory/forcasting')),
  },
  {
    path: '/Inventory/inventory_report',
    label: 'Inventory/inventory_report.php',
    sourcePath: 'templates/Inventory/inventory_report.php',
    Component: lazy(() => import('./pages/Inventory/inventory_report')),
  },
  {
    path: '/Inventory/items',
    label: 'Inventory/items.php',
    sourcePath: 'templates/Inventory/items.php',
    Component: lazy(() => import('./pages/Inventory/items')),
  },
  {
    path: '/Inventory/main_store',
    label: 'Inventory/main_store.php',
    sourcePath: 'templates/Inventory/main_store.php',
    Component: lazy(() => import('./pages/Inventory/main_store')),
  },
  {
    path: '/Inventory/manage',
    label: 'Inventory/manage.php',
    sourcePath: 'templates/Inventory/manage.php',
    Component: lazy(() => import('./pages/Inventory/manage')),
  },
  {
    path: '/Inventory/modal-template',
    label: 'Inventory/modal-template.php',
    sourcePath: 'templates/Inventory/modal-template.php',
    Component: lazy(() => import('./pages/Inventory/modal-template')),
  },
  {
    path: '/Inventory/order_stock_count',
    label: 'Inventory/order_stock_count.php',
    sourcePath: 'templates/Inventory/order_stock_count.php',
    Component: lazy(() => import('./pages/Inventory/order_stock_count')),
  },
  {
    path: '/Inventory/orders',
    label: 'Inventory/orders.php',
    sourcePath: 'templates/Inventory/orders.php',
    Component: lazy(() => import('./pages/Inventory/orders')),
  },
  {
    path: '/Inventory/outlets',
    label: 'Inventory/outlets.php',
    sourcePath: 'templates/Inventory/outlets.php',
    Component: lazy(() => import('./pages/Inventory/outlets')),
  },
  {
    path: '/Inventory/pdf/drug_consumption',
    label: 'Inventory/pdf/drug_consumption.php',
    sourcePath: 'templates/Inventory/pdf/drug_consumption.php',
    Component: lazy(() => import('./pages/Inventory/pdf/drug_consumption')),
  },
  {
    path: '/Inventory/pdf/patient_report',
    label: 'Inventory/pdf/patient_report.php',
    sourcePath: 'templates/Inventory/pdf/patient_report.php',
    Component: lazy(() => import('./pages/Inventory/pdf/patient_report')),
  },
  {
    path: '/Inventory/receive_purchases',
    label: 'Inventory/receive_purchases.php',
    sourcePath: 'templates/Inventory/receive_purchases.php',
    Component: lazy(() => import('./pages/Inventory/receive_purchases')),
  },
  {
    path: '/Inventory/receive_stock',
    label: 'Inventory/receive_stock.php',
    sourcePath: 'templates/Inventory/receive_stock.php',
    Component: lazy(() => import('./pages/Inventory/receive_stock')),
  },
  {
    path: '/Inventory/recipe_viewer',
    label: 'Inventory/recipe_viewer.php',
    sourcePath: 'templates/Inventory/recipe_viewer.php',
    Component: lazy(() => import('./pages/Inventory/recipe_viewer')),
  },
  {
    path: '/Inventory/reconciliations',
    label: 'Inventory/reconciliations.php',
    sourcePath: 'templates/Inventory/reconciliations.php',
    Component: lazy(() => import('./pages/Inventory/reconciliations')),
  },
  {
    path: '/Inventory/stock_count',
    label: 'Inventory/stock_count.php',
    sourcePath: 'templates/Inventory/stock_count.php',
    Component: lazy(() => import('./pages/Inventory/stock_count')),
  },
  {
    path: '/Inventory/stock_count_reconciliation',
    label: 'Inventory/stock_count_reconciliation.php',
    sourcePath: 'templates/Inventory/stock_count_reconciliation.php',
    Component: lazy(() => import('./pages/Inventory/stock_count_reconciliation')),
  },
  {
    path: '/Inventory/stock_transfers',
    label: 'Inventory/stock_transfers.php',
    sourcePath: 'templates/Inventory/stock_transfers.php',
    Component: lazy(() => import('./pages/Inventory/stock_transfers')),
  },
  {
    path: '/Inventory/transfer_list',
    label: 'Inventory/transfer_list.php',
    sourcePath: 'templates/Inventory/transfer_list.php',
    Component: lazy(() => import('./pages/Inventory/transfer_list')),
  },
  {
    path: '/Inventory/transfers',
    label: 'Inventory/transfers.php',
    sourcePath: 'templates/Inventory/transfers.php',
    Component: lazy(() => import('./pages/Inventory/transfers')),
  },
  {
    path: '/Inventory/view_count',
    label: 'Inventory/view_count.php',
    sourcePath: 'templates/Inventory/view_count.php',
    Component: lazy(() => import('./pages/Inventory/view_count')),
  },
  {
    path: '/Inventory/view_purchases',
    label: 'Inventory/view_purchases.php',
    sourcePath: 'templates/Inventory/view_purchases.php',
    Component: lazy(() => import('./pages/Inventory/view_purchases')),
  },
  {
    path: '/Inventory/view_stock_count',
    label: 'Inventory/view_stock_count.php',
    sourcePath: 'templates/Inventory/view_stock_count.php',
    Component: lazy(() => import('./pages/Inventory/view_stock_count')),
  },
  {
    path: '/Inventory/view_stock_reconciliation',
    label: 'Inventory/view_stock_reconciliation.php',
    sourcePath: 'templates/Inventory/view_stock_reconciliation.php',
    Component: lazy(() => import('./pages/Inventory/view_stock_reconciliation')),
  },
  {
    path: '/Inventory/waste',
    label: 'Inventory/waste.php',
    sourcePath: 'templates/Inventory/waste.php',
    Component: lazy(() => import('./pages/Inventory/waste')),
  },
  {
    path: '/Inventory/waste_record',
    label: 'Inventory/waste_record.php',
    sourcePath: 'templates/Inventory/waste_record.php',
    Component: lazy(() => import('./pages/Inventory/waste_record')),
  },
  {
    path: '/InventoryList/manage_equipment',
    label: 'InventoryList/manage_equipment.php',
    sourcePath: 'templates/InventoryList/manage_equipment.php',
    Component: lazy(() => import('./pages/InventoryList/manage_equipment')),
  },
  {
    path: '/InventoryList/record_work_order',
    label: 'InventoryList/record_work_order.php',
    sourcePath: 'templates/InventoryList/record_work_order.php',
    Component: lazy(() => import('./pages/InventoryList/record_work_order')),
  },
  {
    path: '/InventoryList/report',
    label: 'InventoryList/report.php',
    sourcePath: 'templates/InventoryList/report.php',
    Component: lazy(() => import('./pages/InventoryList/report')),
  },
  {
    path: '/InventoryList/work_order_tracker',
    label: 'InventoryList/work_order_tracker.php',
    sourcePath: 'templates/InventoryList/work_order_tracker.php',
    Component: lazy(() => import('./pages/InventoryList/work_order_tracker')),
  },
  {
    path: '/Invoicing/confirm',
    label: 'Invoicing/confirm.php',
    sourcePath: 'templates/Invoicing/confirm.php',
    Component: lazy(() => import('./pages/Invoicing/confirm')),
  },
  {
    path: '/Invoicing/edit',
    label: 'Invoicing/edit.php',
    sourcePath: 'templates/Invoicing/edit.php',
    Component: lazy(() => import('./pages/Invoicing/edit')),
  },
  {
    path: '/Invoicing/index',
    label: 'Invoicing/index.php',
    sourcePath: 'templates/Invoicing/index.php',
    Component: lazy(() => import('./pages/Invoicing/index')),
  },
  {
    path: '/Licences/index',
    label: 'Licences/index.php',
    sourcePath: 'templates/Licences/index.php',
    Component: lazy(() => import('./pages/Licences/index')),
  },
  {
    path: '/ManageInsurances/edit_company_insurance',
    label: 'ManageInsurances/edit_company_insurance.php',
    sourcePath: 'templates/ManageInsurances/edit_company_insurance.php',
    Component: lazy(() => import('./pages/ManageInsurances/edit_company_insurance')),
  },
  {
    path: '/ManageInsurances/edit_private_insurance',
    label: 'ManageInsurances/edit_private_insurance.php',
    sourcePath: 'templates/ManageInsurances/edit_private_insurance.php',
    Component: lazy(() => import('./pages/ManageInsurances/edit_private_insurance')),
  },
  {
    path: '/ManageInsurances/edit_public_insurance',
    label: 'ManageInsurances/edit_public_insurance.php',
    sourcePath: 'templates/ManageInsurances/edit_public_insurance.php',
    Component: lazy(() => import('./pages/ManageInsurances/edit_public_insurance')),
  },
  {
    path: '/ManageLabs/edit_specimen_type_modal',
    label: 'ManageLabs/edit_specimen_type_modal.php',
    sourcePath: 'templates/ManageLabs/edit_specimen_type_modal.php',
    Component: lazy(() => import('./pages/ManageLabs/edit_specimen_type_modal')),
  },
  {
    path: '/ManageLabs/index',
    label: 'ManageLabs/index.php',
    sourcePath: 'templates/ManageLabs/index.php',
    Component: lazy(() => import('./pages/ManageLabs/index')),
  },
  {
    path: '/ManageLabs/pdf/view_lab_test',
    label: 'ManageLabs/pdf/view_lab_test.php',
    sourcePath: 'templates/ManageLabs/pdf/view_lab_test.php',
    Component: lazy(() => import('./pages/ManageLabs/pdf/view_lab_test')),
  },
  {
    path: '/ManageLabs/update_lab_template',
    label: 'ManageLabs/update_lab_template.php',
    sourcePath: 'templates/ManageLabs/update_lab_template.php',
    Component: lazy(() => import('./pages/ManageLabs/update_lab_template')),
  },
  {
    path: '/ManageLabs/view_lab_test',
    label: 'ManageLabs/view_lab_test.php',
    sourcePath: 'templates/ManageLabs/view_lab_test.php',
    Component: lazy(() => import('./pages/ManageLabs/view_lab_test')),
  },
  {
    path: '/ManageRadiologies/index',
    label: 'ManageRadiologies/index.php',
    sourcePath: 'templates/ManageRadiologies/index.php',
    Component: lazy(() => import('./pages/ManageRadiologies/index')),
  },
  {
    path: '/ManageRadiologies/update_scan_template',
    label: 'ManageRadiologies/update_scan_template.php',
    sourcePath: 'templates/ManageRadiologies/update_scan_template.php',
    Component: lazy(() => import('./pages/ManageRadiologies/update_scan_template')),
  },
  {
    path: '/ManageSecurity/edit_specialties',
    label: 'ManageSecurity/edit_specialties.php',
    sourcePath: 'templates/ManageSecurity/edit_specialties.php',
    Component: lazy(() => import('./pages/ManageSecurity/edit_specialties')),
  },
  {
    path: '/ManageSecurity/index',
    label: 'ManageSecurity/index.php',
    sourcePath: 'templates/ManageSecurity/index.php',
    Component: lazy(() => import('./pages/ManageSecurity/index')),
  },
  {
    path: '/ManageServices/index',
    label: 'ManageServices/index.php',
    sourcePath: 'templates/ManageServices/index.php',
    Component: lazy(() => import('./pages/ManageServices/index')),
  },
  {
    path: '/ManageServices/update_lab_template',
    label: 'ManageServices/update_lab_template.php',
    sourcePath: 'templates/ManageServices/update_lab_template.php',
    Component: lazy(() => import('./pages/ManageServices/update_lab_template')),
  },
  {
    path: '/ManageWards/index',
    label: 'ManageWards/index.php',
    sourcePath: 'templates/ManageWards/index.php',
    Component: lazy(() => import('./pages/ManageWards/index')),
  },
  {
    path: '/Notifications/index',
    label: 'Notifications/index.php',
    sourcePath: 'templates/Notifications/index.php',
    Component: lazy(() => import('./pages/Notifications/index')),
  },
  {
    path: '/NurseStation/index',
    label: 'NurseStation/index.php',
    sourcePath: 'templates/NurseStation/index.php',
    Component: lazy(() => import('./pages/NurseStation/index')),
  },
  {
    path: '/NurseStation/new_nurse_notes',
    label: 'NurseStation/new_nurse_notes.php',
    sourcePath: 'templates/NurseStation/new_nurse_notes.php',
    Component: lazy(() => import('./pages/NurseStation/new_nurse_notes')),
  },
  {
    path: '/NurseStation/nurse_handoff',
    label: 'NurseStation/nurse_handoff.php',
    sourcePath: 'templates/NurseStation/nurse_handoff.php',
    Component: lazy(() => import('./pages/NurseStation/nurse_handoff')),
  },
  {
    path: '/NurseStation/view_nurse_handoff',
    label: 'NurseStation/view_nurse_handoff.php',
    sourcePath: 'templates/NurseStation/view_nurse_handoff.php',
    Component: lazy(() => import('./pages/NurseStation/view_nurse_handoff')),
  },
  {
    path: '/OrPlanner/index',
    label: 'OrPlanner/index.php',
    sourcePath: 'templates/OrPlanner/index.php',
    Component: lazy(() => import('./pages/OrPlanner/index')),
  },
  {
    path: '/OrPlanner/view_patient_surgery',
    label: 'OrPlanner/view_patient_surgery.php',
    sourcePath: 'templates/OrPlanner/view_patient_surgery.php',
    Component: lazy(() => import('./pages/OrPlanner/view_patient_surgery')),
  },
  {
    path: '/Outlets/index',
    label: 'Outlets/index.php',
    sourcePath: 'templates/Outlets/index.php',
    Component: lazy(() => import('./pages/Outlets/index')),
  },
  {
    path: '/PartnerCompanies/add',
    label: 'PartnerCompanies/add.php',
    sourcePath: 'templates/PartnerCompanies/add.php',
    Component: lazy(() => import('./pages/PartnerCompanies/add')),
  },
  {
    path: '/PartnerCompanies/edit',
    label: 'PartnerCompanies/edit.php',
    sourcePath: 'templates/PartnerCompanies/edit.php',
    Component: lazy(() => import('./pages/PartnerCompanies/edit')),
  },
  {
    path: '/PartnerCompanies/index',
    label: 'PartnerCompanies/index.php',
    sourcePath: 'templates/PartnerCompanies/index.php',
    Component: lazy(() => import('./pages/PartnerCompanies/index')),
  },
  {
    path: '/PartnerCompanies/view',
    label: 'PartnerCompanies/view.php',
    sourcePath: 'templates/PartnerCompanies/view.php',
    Component: lazy(() => import('./pages/PartnerCompanies/view')),
  },
  {
    path: '/Patients/add_patient',
    label: 'Patients/add_patient.php',
    sourcePath: 'templates/Patients/add_patient.php',
    Component: lazy(() => import('./pages/Patients/add_patient')),
  },
  {
    path: '/Patients/add_walkin_patient',
    label: 'Patients/add_walkin_patient.php',
    sourcePath: 'templates/Patients/add_walkin_patient.php',
    Component: lazy(() => import('./pages/Patients/add_walkin_patient')),
  },
  {
    path: '/Patients/chiro_assessment_plan_visit_report',
    label: 'Patients/chiro_assessment_plan_visit_report.php',
    sourcePath: 'templates/Patients/chiro_assessment_plan_visit_report.php',
    Component: lazy(() => import('./pages/Patients/chiro_assessment_plan_visit_report')),
  },
  {
    path: '/Patients/chiro_notes_visit_report',
    label: 'Patients/chiro_notes_visit_report.php',
    sourcePath: 'templates/Patients/chiro_notes_visit_report.php',
    Component: lazy(() => import('./pages/Patients/chiro_notes_visit_report')),
  },
  {
    path: '/Patients/chiro_space',
    label: 'Patients/chiro_space.php',
    sourcePath: 'templates/Patients/chiro_space.php',
    Component: lazy(() => import('./pages/Patients/chiro_space')),
  },
  {
    path: '/Patients/clinical_quality_dashboard',
    label: 'Patients/clinical_quality_dashboard.php',
    sourcePath: 'templates/Patients/clinical_quality_dashboard.php',
    Component: lazy(() => import('./pages/Patients/clinical_quality_dashboard')),
  },
  {
    path: '/Patients/dashboard',
    label: 'Patients/dashboard.php',
    sourcePath: 'templates/Patients/dashboard.php',
    Component: lazy(() => import('./pages/Patients/dashboard')),
  },
  {
    path: '/Patients/edit_patient',
    label: 'Patients/edit_patient.php',
    sourcePath: 'templates/Patients/edit_patient.php',
    Component: lazy(() => import('./pages/Patients/edit_patient')),
  },
  {
    path: '/Patients/executive_summary_dashboard',
    label: 'Patients/executive_summary_dashboard.php',
    sourcePath: 'templates/Patients/executive_summary_dashboard.php',
    Component: lazy(() => import('./pages/Patients/executive_summary_dashboard')),
  },
  {
    path: '/Patients/eye_space',
    label: 'Patients/eye_space.php',
    sourcePath: 'templates/Patients/eye_space.php',
    Component: lazy(() => import('./pages/Patients/eye_space')),
  },
  {
    path: '/Patients/financial_dashboard',
    label: 'Patients/financial_dashboard.php',
    sourcePath: 'templates/Patients/financial_dashboard.php',
    Component: lazy(() => import('./pages/Patients/financial_dashboard')),
  },
  {
    path: '/Patients/inpatient_report',
    label: 'Patients/inpatient_report.php',
    sourcePath: 'templates/Patients/inpatient_report.php',
    Component: lazy(() => import('./pages/Patients/inpatient_report')),
  },
  {
    path: '/Patients/json/update_procedures',
    label: 'Patients/json/update_procedures.php',
    sourcePath: 'templates/Patients/json/update_procedures.php',
    Component: lazy(() => import('./pages/Patients/json/update_procedures')),
  },
  {
    path: '/Patients/maternal_visits',
    label: 'Patients/maternal_visits.php',
    sourcePath: 'templates/Patients/maternal_visits.php',
    Component: lazy(() => import('./pages/Patients/maternal_visits')),
  },
  {
    path: '/Patients/operation_efficiency',
    label: 'Patients/operation_efficiency.php',
    sourcePath: 'templates/Patients/operation_efficiency.php',
    Component: lazy(() => import('./pages/Patients/operation_efficiency')),
  },
  {
    path: '/Patients/outpatient_report',
    label: 'Patients/outpatient_report.php',
    sourcePath: 'templates/Patients/outpatient_report.php',
    Component: lazy(() => import('./pages/Patients/outpatient_report')),
  },
  {
    path: '/Patients/patient_bill',
    label: 'Patients/patient_bill.php',
    sourcePath: 'templates/Patients/patient_bill.php',
    Component: lazy(() => import('./pages/Patients/patient_bill')),
  },
  {
    path: '/Patients/patient_insurance_expiry',
    label: 'Patients/patient_insurance_expiry.php',
    sourcePath: 'templates/Patients/patient_insurance_expiry.php',
    Component: lazy(() => import('./pages/Patients/patient_insurance_expiry')),
  },
  {
    path: '/Patients/patient_sessions_view',
    label: 'Patients/patient_sessions_view.php',
    sourcePath: 'templates/Patients/patient_sessions_view.php',
    Component: lazy(() => import('./pages/Patients/patient_sessions_view')),
  },
  {
    path: '/Patients/pdf/drug_administration_chart',
    label: 'Patients/pdf/drug_administration_chart.php',
    sourcePath: 'templates/Patients/pdf/drug_administration_chart.php',
    Component: lazy(() => import('./pages/Patients/pdf/drug_administration_chart')),
  },
  {
    path: '/Patients/pdf/referral_report',
    label: 'Patients/pdf/referral_report.php',
    sourcePath: 'templates/Patients/pdf/referral_report.php',
    Component: lazy(() => import('./pages/Patients/pdf/referral_report')),
  },
  {
    path: '/Patients/pdf/routine',
    label: 'Patients/pdf/routine.php',
    sourcePath: 'templates/Patients/pdf/routine.php',
    Component: lazy(() => import('./pages/Patients/pdf/routine')),
  },
  {
    path: '/Patients/pdf/view_patient_profile',
    label: 'Patients/pdf/view_patient_profile.php',
    sourcePath: 'templates/Patients/pdf/view_patient_profile.php',
    Component: lazy(() => import('./pages/Patients/pdf/view_patient_profile')),
  },
  {
    path: '/Patients/pdf/visit_report',
    label: 'Patients/pdf/visit_report.php',
    sourcePath: 'templates/Patients/pdf/visit_report.php',
    Component: lazy(() => import('./pages/Patients/pdf/visit_report')),
  },
  {
    path: '/Patients/population_health_dashboard',
    label: 'Patients/population_health_dashboard.php',
    sourcePath: 'templates/Patients/population_health_dashboard.php',
    Component: lazy(() => import('./pages/Patients/population_health_dashboard')),
  },
  {
    path: '/Patients/prerounding',
    label: 'Patients/prerounding.php',
    sourcePath: 'templates/Patients/prerounding.php',
    Component: lazy(() => import('./pages/Patients/prerounding')),
  },
  {
    path: '/Patients/provider_productivity',
    label: 'Patients/provider_productivity.php',
    sourcePath: 'templates/Patients/provider_productivity.php',
    Component: lazy(() => import('./pages/Patients/provider_productivity')),
  },
  {
    path: '/Patients/referal_report',
    label: 'Patients/referal_report.php',
    sourcePath: 'templates/Patients/referal_report.php',
    Component: lazy(() => import('./pages/Patients/referal_report')),
  },
  {
    path: '/Patients/routine_care_report',
    label: 'Patients/routine_care_report.php',
    sourcePath: 'templates/Patients/routine_care_report.php',
    Component: lazy(() => import('./pages/Patients/routine_care_report')),
  },
  {
    path: '/Patients/selective_patient_bill',
    label: 'Patients/selective_patient_bill.php',
    sourcePath: 'templates/Patients/selective_patient_bill.php',
    Component: lazy(() => import('./pages/Patients/selective_patient_bill')),
  },
  {
    path: '/Patients/single_chiro_assessment_plan_visit_report',
    label: 'Patients/single_chiro_assessment_plan_visit_report.php',
    sourcePath: 'templates/Patients/single_chiro_assessment_plan_visit_report.php',
    Component: lazy(() => import('./pages/Patients/single_chiro_assessment_plan_visit_report')),
  },
  {
    path: '/Patients/view_maternity',
    label: 'Patients/view_maternity.php',
    sourcePath: 'templates/Patients/view_maternity.php',
    Component: lazy(() => import('./pages/Patients/view_maternity')),
  },
  {
    path: '/Patients/view_maternity_1',
    label: 'Patients/view_maternity_1.php',
    sourcePath: 'templates/Patients/view_maternity_1.php',
    Component: lazy(() => import('./pages/Patients/view_maternity_1')),
  },
  {
    path: '/Patients/view_opd_visits',
    label: 'Patients/view_opd_visits.php',
    sourcePath: 'templates/Patients/view_opd_visits.php',
    Component: lazy(() => import('./pages/Patients/view_opd_visits')),
  },
  {
    path: '/Patients/view_patient',
    label: 'Patients/view_patient.php',
    sourcePath: 'templates/Patients/view_patient.php',
    Component: lazy(() => import('./pages/Patients/view_patient')),
  },
  {
    path: '/Patients/view_patient_examination',
    label: 'Patients/view_patient_examination.php',
    sourcePath: 'templates/Patients/view_patient_examination.php',
    Component: lazy(() => import('./pages/Patients/view_patient_examination')),
  },
  {
    path: '/Patients/view_patient_flow',
    label: 'Patients/view_patient_flow.php',
    sourcePath: 'templates/Patients/view_patient_flow.php',
    Component: lazy(() => import('./pages/Patients/view_patient_flow')),
  },
  {
    path: '/Patients/view_patient_history',
    label: 'Patients/view_patient_history.php',
    sourcePath: 'templates/Patients/view_patient_history.php',
    Component: lazy(() => import('./pages/Patients/view_patient_history')),
  },
  {
    path: '/Patients/view_patient_note',
    label: 'Patients/view_patient_note.php',
    sourcePath: 'templates/Patients/view_patient_note.php',
    Component: lazy(() => import('./pages/Patients/view_patient_note')),
  },
  {
    path: '/Patients/view_patients',
    label: 'Patients/view_patients.php',
    sourcePath: 'templates/Patients/view_patients.php',
    Component: lazy(() => import('./pages/Patients/view_patients')),
  },
  {
    path: '/Patients/view_patients_employee',
    label: 'Patients/view_patients_employee.php',
    sourcePath: 'templates/Patients/view_patients_employee.php',
    Component: lazy(() => import('./pages/Patients/view_patients_employee')),
  },
  {
    path: '/Patients/view_patients_routine_care',
    label: 'Patients/view_patients_routine_care.php',
    sourcePath: 'templates/Patients/view_patients_routine_care.php',
    Component: lazy(() => import('./pages/Patients/view_patients_routine_care')),
  },
  {
    path: '/Patients/view_visit',
    label: 'Patients/view_visit.php',
    sourcePath: 'templates/Patients/view_visit.php',
    Component: lazy(() => import('./pages/Patients/view_visit')),
  },
  {
    path: '/Patients/view_visit_report',
    label: 'Patients/view_visit_report.php',
    sourcePath: 'templates/Patients/view_visit_report.php',
    Component: lazy(() => import('./pages/Patients/view_visit_report')),
  },
  {
    path: '/Patients/view_visits',
    label: 'Patients/view_visits.php',
    sourcePath: 'templates/Patients/view_visits.php',
    Component: lazy(() => import('./pages/Patients/view_visits')),
  },
  {
    path: '/Patients/view_visits_ipd',
    label: 'Patients/view_visits_ipd.php',
    sourcePath: 'templates/Patients/view_visits_ipd.php',
    Component: lazy(() => import('./pages/Patients/view_visits_ipd')),
  },
  {
    path: '/Patients/visit_mini',
    label: 'Patients/visit_mini.php',
    sourcePath: 'templates/Patients/visit_mini.php',
    Component: lazy(() => import('./pages/Patients/visit_mini')),
  },
  {
    path: '/Patients/visit_report',
    label: 'Patients/visit_report.php',
    sourcePath: 'templates/Patients/visit_report.php',
    Component: lazy(() => import('./pages/Patients/visit_report')),
  },
  {
    path: '/PatientVisitDiagnoses/edit_diagnoses',
    label: 'PatientVisitDiagnoses/edit_diagnoses.php',
    sourcePath: 'templates/PatientVisitDiagnoses/edit_diagnoses.php',
    Component: lazy(() => import('./pages/PatientVisitDiagnoses/edit_diagnoses')),
  },
  {
    path: '/PatientVisitDoctorNotes/add',
    label: 'PatientVisitDoctorNotes/add.php',
    sourcePath: 'templates/PatientVisitDoctorNotes/add.php',
    Component: lazy(() => import('./pages/PatientVisitDoctorNotes/add')),
  },
  {
    path: '/PatientVisitDoctorNotes/edit',
    label: 'PatientVisitDoctorNotes/edit.php',
    sourcePath: 'templates/PatientVisitDoctorNotes/edit.php',
    Component: lazy(() => import('./pages/PatientVisitDoctorNotes/edit')),
  },
  {
    path: '/PatientVisitDoctorNotes/edit_doctor_note',
    label: 'PatientVisitDoctorNotes/edit_doctor_note.php',
    sourcePath: 'templates/PatientVisitDoctorNotes/edit_doctor_note.php',
    Component: lazy(() => import('./pages/PatientVisitDoctorNotes/edit_doctor_note')),
  },
  {
    path: '/PatientVisitDoctorNotes/get_all_doctor_notes',
    label: 'PatientVisitDoctorNotes/get_all_doctor_notes.php',
    sourcePath: 'templates/PatientVisitDoctorNotes/get_all_doctor_notes.php',
    Component: lazy(() => import('./pages/PatientVisitDoctorNotes/get_all_doctor_notes')),
  },
  {
    path: '/PatientVisitDoctorNotes/index',
    label: 'PatientVisitDoctorNotes/index.php',
    sourcePath: 'templates/PatientVisitDoctorNotes/index.php',
    Component: lazy(() => import('./pages/PatientVisitDoctorNotes/index')),
  },
  {
    path: '/PatientVisitDoctorNotes/view',
    label: 'PatientVisitDoctorNotes/view.php',
    sourcePath: 'templates/PatientVisitDoctorNotes/view.php',
    Component: lazy(() => import('./pages/PatientVisitDoctorNotes/view')),
  },
  {
    path: '/PatientVisitFluids/edit_fluid',
    label: 'PatientVisitFluids/edit_fluid.php',
    sourcePath: 'templates/PatientVisitFluids/edit_fluid.php',
    Component: lazy(() => import('./pages/PatientVisitFluids/edit_fluid')),
  },
  {
    path: '/PatientVisitFollowups/edit_followup',
    label: 'PatientVisitFollowups/edit_followup.php',
    sourcePath: 'templates/PatientVisitFollowups/edit_followup.php',
    Component: lazy(() => import('./pages/PatientVisitFollowups/edit_followup')),
  },
  {
    path: '/PatientVisitMedicationTasks/add',
    label: 'PatientVisitMedicationTasks/add.php',
    sourcePath: 'templates/PatientVisitMedicationTasks/add.php',
    Component: lazy(() => import('./pages/PatientVisitMedicationTasks/add')),
  },
  {
    path: '/PatientVisitMedicationTasks/edit',
    label: 'PatientVisitMedicationTasks/edit.php',
    sourcePath: 'templates/PatientVisitMedicationTasks/edit.php',
    Component: lazy(() => import('./pages/PatientVisitMedicationTasks/edit')),
  },
  {
    path: '/PatientVisitMedicationTasks/index',
    label: 'PatientVisitMedicationTasks/index.php',
    sourcePath: 'templates/PatientVisitMedicationTasks/index.php',
    Component: lazy(() => import('./pages/PatientVisitMedicationTasks/index')),
  },
  {
    path: '/PatientVisitMedicationTasks/view',
    label: 'PatientVisitMedicationTasks/view.php',
    sourcePath: 'templates/PatientVisitMedicationTasks/view.php',
    Component: lazy(() => import('./pages/PatientVisitMedicationTasks/view')),
  },
  {
    path: '/PatientVisitMiscellaneousTasks/add',
    label: 'PatientVisitMiscellaneousTasks/add.php',
    sourcePath: 'templates/PatientVisitMiscellaneousTasks/add.php',
    Component: lazy(() => import('./pages/PatientVisitMiscellaneousTasks/add')),
  },
  {
    path: '/PatientVisitMiscellaneousTasks/edit',
    label: 'PatientVisitMiscellaneousTasks/edit.php',
    sourcePath: 'templates/PatientVisitMiscellaneousTasks/edit.php',
    Component: lazy(() => import('./pages/PatientVisitMiscellaneousTasks/edit')),
  },
  {
    path: '/PatientVisitMiscellaneousTasks/index',
    label: 'PatientVisitMiscellaneousTasks/index.php',
    sourcePath: 'templates/PatientVisitMiscellaneousTasks/index.php',
    Component: lazy(() => import('./pages/PatientVisitMiscellaneousTasks/index')),
  },
  {
    path: '/PatientVisitMiscellaneousTasks/view',
    label: 'PatientVisitMiscellaneousTasks/view.php',
    sourcePath: 'templates/PatientVisitMiscellaneousTasks/view.php',
    Component: lazy(() => import('./pages/PatientVisitMiscellaneousTasks/view')),
  },
  {
    path: '/PatientVisitNurseNotes/edit_nurse_note',
    label: 'PatientVisitNurseNotes/edit_nurse_note.php',
    sourcePath: 'templates/PatientVisitNurseNotes/edit_nurse_note.php',
    Component: lazy(() => import('./pages/PatientVisitNurseNotes/edit_nurse_note')),
  },
  {
    path: '/PatientVisitNurseNotes/get_all_nurse_notes',
    label: 'PatientVisitNurseNotes/get_all_nurse_notes.php',
    sourcePath: 'templates/PatientVisitNurseNotes/get_all_nurse_notes.php',
    Component: lazy(() => import('./pages/PatientVisitNurseNotes/get_all_nurse_notes')),
  },
  {
    path: '/PatientVisitPrnTasks/add',
    label: 'PatientVisitPrnTasks/add.php',
    sourcePath: 'templates/PatientVisitPrnTasks/add.php',
    Component: lazy(() => import('./pages/PatientVisitPrnTasks/add')),
  },
  {
    path: '/PatientVisitPrnTasks/edit',
    label: 'PatientVisitPrnTasks/edit.php',
    sourcePath: 'templates/PatientVisitPrnTasks/edit.php',
    Component: lazy(() => import('./pages/PatientVisitPrnTasks/edit')),
  },
  {
    path: '/PatientVisitPrnTasks/index',
    label: 'PatientVisitPrnTasks/index.php',
    sourcePath: 'templates/PatientVisitPrnTasks/index.php',
    Component: lazy(() => import('./pages/PatientVisitPrnTasks/index')),
  },
  {
    path: '/PatientVisitPrnTasks/view',
    label: 'PatientVisitPrnTasks/view.php',
    sourcePath: 'templates/PatientVisitPrnTasks/view.php',
    Component: lazy(() => import('./pages/PatientVisitPrnTasks/view')),
  },
  {
    path: '/PatientVisits/all_patient_odqs',
    label: 'PatientVisits/all_patient_odqs.php',
    sourcePath: 'templates/PatientVisits/all_patient_odqs.php',
    Component: lazy(() => import('./pages/PatientVisits/all_patient_odqs')),
  },
  {
    path: '/PatientVisits/analyze_patient_odqs',
    label: 'PatientVisits/analyze_patient_odqs.php',
    sourcePath: 'templates/PatientVisits/analyze_patient_odqs.php',
    Component: lazy(() => import('./pages/PatientVisits/analyze_patient_odqs')),
  },
  {
    path: '/PatientVisits/careflow_condition_builder',
    label: 'PatientVisits/careflow_condition_builder.php',
    sourcePath: 'templates/PatientVisits/careflow_condition_builder.php',
    Component: lazy(() => import('./pages/PatientVisits/careflow_condition_builder')),
  },
  {
    path: '/PatientVisits/clinical_pathways',
    label: 'PatientVisits/clinical_pathways.php',
    sourcePath: 'templates/PatientVisits/clinical_pathways.php',
    Component: lazy(() => import('./pages/PatientVisits/clinical_pathways')),
  },
  {
    path: '/PatientVisits/discharge_summary',
    label: 'PatientVisits/discharge_summary.php',
    sourcePath: 'templates/PatientVisits/discharge_summary.php',
    Component: lazy(() => import('./pages/PatientVisits/discharge_summary')),
  },
  {
    path: '/PatientVisits/discharge_summary_cancelled',
    label: 'PatientVisits/discharge_summary_cancelled.php',
    sourcePath: 'templates/PatientVisits/discharge_summary_cancelled.php',
    Component: lazy(() => import('./pages/PatientVisits/discharge_summary_cancelled')),
  },
  {
    path: '/PatientVisits/edit_patient_odqs',
    label: 'PatientVisits/edit_patient_odqs.php',
    sourcePath: 'templates/PatientVisits/edit_patient_odqs.php',
    Component: lazy(() => import('./pages/PatientVisits/edit_patient_odqs')),
  },
  {
    path: '/PatientVisits/get_all_patient_encounter_note',
    label: 'PatientVisits/get_all_patient_encounter_note.php',
    sourcePath: 'templates/PatientVisits/get_all_patient_encounter_note.php',
    Component: lazy(() => import('./pages/PatientVisits/get_all_patient_encounter_note')),
  },
  {
    path: '/PatientVisits/get_queue_manager',
    label: 'PatientVisits/get_queue_manager.php',
    sourcePath: 'templates/PatientVisits/get_queue_manager.php',
    Component: lazy(() => import('./pages/PatientVisits/get_queue_manager')),
  },
  {
    path: '/PatientVisits/passed_away_outcome',
    label: 'PatientVisits/passed_away_outcome.php',
    sourcePath: 'templates/PatientVisits/passed_away_outcome.php',
    Component: lazy(() => import('./pages/PatientVisits/passed_away_outcome')),
  },
  {
    path: '/PatientVisits/patient_absconded_outcome',
    label: 'PatientVisits/patient_absconded_outcome.php',
    sourcePath: 'templates/PatientVisits/patient_absconded_outcome.php',
    Component: lazy(() => import('./pages/PatientVisits/patient_absconded_outcome')),
  },
  {
    path: '/PatientVisits/view_patient',
    label: 'PatientVisits/view_patient.php',
    sourcePath: 'templates/PatientVisits/view_patient.php',
    Component: lazy(() => import('./pages/PatientVisits/view_patient')),
  },
  {
    path: '/PatientVisits/visit_space_build',
    label: 'PatientVisits/visit_space_build.php',
    sourcePath: 'templates/PatientVisits/visit_space_build.php',
    Component: lazy(() => import('./pages/PatientVisits/visit_space_build')),
  },
  {
    path: '/PatientVisitServiceTasks/add',
    label: 'PatientVisitServiceTasks/add.php',
    sourcePath: 'templates/PatientVisitServiceTasks/add.php',
    Component: lazy(() => import('./pages/PatientVisitServiceTasks/add')),
  },
  {
    path: '/PatientVisitServiceTasks/edit',
    label: 'PatientVisitServiceTasks/edit.php',
    sourcePath: 'templates/PatientVisitServiceTasks/edit.php',
    Component: lazy(() => import('./pages/PatientVisitServiceTasks/edit')),
  },
  {
    path: '/PatientVisitServiceTasks/index',
    label: 'PatientVisitServiceTasks/index.php',
    sourcePath: 'templates/PatientVisitServiceTasks/index.php',
    Component: lazy(() => import('./pages/PatientVisitServiceTasks/index')),
  },
  {
    path: '/PatientVisitServiceTasks/view',
    label: 'PatientVisitServiceTasks/view.php',
    sourcePath: 'templates/PatientVisitServiceTasks/view.php',
    Component: lazy(() => import('./pages/PatientVisitServiceTasks/view')),
  },
  {
    path: '/PatientVisitTreatments/edit_treatment',
    label: 'PatientVisitTreatments/edit_treatment.php',
    sourcePath: 'templates/PatientVisitTreatments/edit_treatment.php',
    Component: lazy(() => import('./pages/PatientVisitTreatments/edit_treatment')),
  },
  {
    path: '/PatientVisitVitals/edit_vitals',
    label: 'PatientVisitVitals/edit_vitals.php',
    sourcePath: 'templates/PatientVisitVitals/edit_vitals.php',
    Component: lazy(() => import('./pages/PatientVisitVitals/edit_vitals')),
  },
  {
    path: '/Pay/invoice',
    label: 'Pay/invoice.php',
    sourcePath: 'templates/Pay/invoice.php',
    Component: lazy(() => import('./pages/Pay/invoice')),
  },
  {
    path: '/Pay/receipt',
    label: 'Pay/receipt.php',
    sourcePath: 'templates/Pay/receipt.php',
    Component: lazy(() => import('./pages/Pay/receipt')),
  },
  {
    path: '/Payments/index',
    label: 'Payments/index.php',
    sourcePath: 'templates/Payments/index.php',
    Component: lazy(() => import('./pages/Payments/index')),
  },
  {
    path: '/Pdf/claim',
    label: 'Pdf/claim.php',
    sourcePath: 'templates/Pdf/claim.php',
    Component: lazy(() => import('./pages/Pdf/claim')),
  },
  {
    path: '/Pdf/routine',
    label: 'Pdf/routine.php',
    sourcePath: 'templates/Pdf/routine.php',
    Component: lazy(() => import('./pages/Pdf/routine')),
  },
  {
    path: '/Pdf/visit_report',
    label: 'Pdf/visit_report.php',
    sourcePath: 'templates/Pdf/visit_report.php',
    Component: lazy(() => import('./pages/Pdf/visit_report')),
  },
  {
    path: '/PendingRequests/index',
    label: 'PendingRequests/index.php',
    sourcePath: 'templates/PendingRequests/index.php',
    Component: lazy(() => import('./pages/PendingRequests/index')),
  },
  {
    path: '/Queue/doctor',
    label: 'Queue/doctor.php',
    sourcePath: 'templates/Queue/doctor.php',
    Component: lazy(() => import('./pages/Queue/doctor')),
  },
  {
    path: '/Queue/nurse',
    label: 'Queue/nurse.php',
    sourcePath: 'templates/Queue/nurse.php',
    Component: lazy(() => import('./pages/Queue/nurse')),
  },
  {
    path: '/ReportQueries/alo',
    label: 'ReportQueries/alo.php',
    sourcePath: 'templates/ReportQueries/alo.php',
    Component: lazy(() => import('./pages/ReportQueries/alo')),
  },
  {
    path: '/ReportQueries/clinical',
    label: 'ReportQueries/clinical.php',
    sourcePath: 'templates/ReportQueries/clinical.php',
    Component: lazy(() => import('./pages/ReportQueries/clinical')),
  },
  {
    path: '/ReportQueries/dashboard',
    label: 'ReportQueries/dashboard.php',
    sourcePath: 'templates/ReportQueries/dashboard.php',
    Component: lazy(() => import('./pages/ReportQueries/dashboard')),
  },
  {
    path: '/ReportQueries/index',
    label: 'ReportQueries/index.php',
    sourcePath: 'templates/ReportQueries/index.php',
    Component: lazy(() => import('./pages/ReportQueries/index')),
  },
  {
    path: '/ReportQueries/lab_analytics_report',
    label: 'ReportQueries/lab_analytics_report.php',
    sourcePath: 'templates/ReportQueries/lab_analytics_report.php',
    Component: lazy(() => import('./pages/ReportQueries/lab_analytics_report')),
  },
  {
    path: '/ReportQueries/medicine_availability',
    label: 'ReportQueries/medicine_availability.php',
    sourcePath: 'templates/ReportQueries/medicine_availability.php',
    Component: lazy(() => import('./pages/ReportQueries/medicine_availability')),
  },
  {
    path: '/ReportQueries/patient_basic',
    label: 'ReportQueries/patient_basic.php',
    sourcePath: 'templates/ReportQueries/patient_basic.php',
    Component: lazy(() => import('./pages/ReportQueries/patient_basic')),
  },
  {
    path: '/ReportQueries/price_adjustment_report',
    label: 'ReportQueries/price_adjustment_report.php',
    sourcePath: 'templates/ReportQueries/price_adjustment_report.php',
    Component: lazy(() => import('./pages/ReportQueries/price_adjustment_report')),
  },
  {
    path: '/ReportQueries/sales_report',
    label: 'ReportQueries/sales_report.php',
    sourcePath: 'templates/ReportQueries/sales_report.php',
    Component: lazy(() => import('./pages/ReportQueries/sales_report')),
  },
  {
    path: '/ReportQueries/view',
    label: 'ReportQueries/view.php',
    sourcePath: 'templates/ReportQueries/view.php',
    Component: lazy(() => import('./pages/ReportQueries/view')),
  },
  {
    path: '/Reports/claims',
    label: 'Reports/claims.php',
    sourcePath: 'templates/Reports/claims.php',
    Component: lazy(() => import('./pages/Reports/claims')),
  },
  {
    path: '/Reports/notifications',
    label: 'Reports/notifications.php',
    sourcePath: 'templates/Reports/notifications.php',
    Component: lazy(() => import('./pages/Reports/notifications')),
  },
  {
    path: '/Reports/pdf/notifications',
    label: 'Reports/pdf/notifications.php',
    sourcePath: 'templates/Reports/pdf/notifications.php',
    Component: lazy(() => import('./pages/Reports/pdf/notifications')),
  },
  {
    path: '/Reports_2021_03_11/claims',
    label: 'Reports_2021_03_11/claims.php',
    sourcePath: 'templates/Reports_2021_03_11/claims.php',
    Component: lazy(() => import('./pages/Reports_2021_03_11/claims')),
  },
  {
    path: '/Reports_2021_03_11/drug_consumption',
    label: 'Reports_2021_03_11/drug_consumption.php',
    sourcePath: 'templates/Reports_2021_03_11/drug_consumption.php',
    Component: lazy(() => import('./pages/Reports_2021_03_11/drug_consumption')),
  },
  {
    path: '/Reports_2021_03_11/pdf/drug_consumption',
    label: 'Reports_2021_03_11/pdf/drug_consumption.php',
    sourcePath: 'templates/Reports_2021_03_11/pdf/drug_consumption.php',
    Component: lazy(() => import('./pages/Reports_2021_03_11/pdf/drug_consumption')),
  },
  {
    path: '/Reports_old/claims',
    label: 'Reports_old/claims.php',
    sourcePath: 'templates/Reports_old/claims.php',
    Component: lazy(() => import('./pages/Reports_old/claims')),
  },
  {
    path: '/Reports_old/notifications',
    label: 'Reports_old/notifications.php',
    sourcePath: 'templates/Reports_old/notifications.php',
    Component: lazy(() => import('./pages/Reports_old/notifications')),
  },
  {
    path: '/Reports_old/pdf/notifications',
    label: 'Reports_old/pdf/notifications.php',
    sourcePath: 'templates/Reports_old/pdf/notifications.php',
    Component: lazy(() => import('./pages/Reports_old/pdf/notifications')),
  },
  {
    path: '/RequestApproval/index',
    label: 'RequestApproval/index.php',
    sourcePath: 'templates/RequestApproval/index.php',
    Component: lazy(() => import('./pages/RequestApproval/index')),
  },
  {
    path: '/RequestLabs/analysis',
    label: 'RequestLabs/analysis.php',
    sourcePath: 'templates/RequestLabs/analysis.php',
    Component: lazy(() => import('./pages/RequestLabs/analysis')),
  },
  {
    path: '/RequestLabs/complete_bom_details',
    label: 'RequestLabs/complete_bom_details.php',
    sourcePath: 'templates/RequestLabs/complete_bom_details.php',
    Component: lazy(() => import('./pages/RequestLabs/complete_bom_details')),
  },
  {
    path: '/RequestLabs/email_patient_visit_report',
    label: 'RequestLabs/email_patient_visit_report.php',
    sourcePath: 'templates/RequestLabs/email_patient_visit_report.php',
    Component: lazy(() => import('./pages/RequestLabs/email_patient_visit_report')),
  },
  {
    path: '/RequestLabs/index',
    label: 'RequestLabs/index.php',
    sourcePath: 'templates/RequestLabs/index.php',
    Component: lazy(() => import('./pages/RequestLabs/index')),
  },
  {
    path: '/RequestLabs/lab_test_history',
    label: 'RequestLabs/lab_test_history.php',
    sourcePath: 'templates/RequestLabs/lab_test_history.php',
    Component: lazy(() => import('./pages/RequestLabs/lab_test_history')),
  },
  {
    path: '/RequestLabs/lab_test_result',
    label: 'RequestLabs/lab_test_result.php',
    sourcePath: 'templates/RequestLabs/lab_test_result.php',
    Component: lazy(() => import('./pages/RequestLabs/lab_test_result')),
  },
  {
    path: '/RequestLabs/loaded_lab_template',
    label: 'RequestLabs/loaded_lab_template.php',
    sourcePath: 'templates/RequestLabs/loaded_lab_template.php',
    Component: lazy(() => import('./pages/RequestLabs/loaded_lab_template')),
  },
  {
    path: '/RequestLabs/patient_report',
    label: 'RequestLabs/patient_report.php',
    sourcePath: 'templates/RequestLabs/patient_report.php',
    Component: lazy(() => import('./pages/RequestLabs/patient_report')),
  },
  {
    path: '/RequestLabs/patient_visit_lab_report',
    label: 'RequestLabs/patient_visit_lab_report.php',
    sourcePath: 'templates/RequestLabs/patient_visit_lab_report.php',
    Component: lazy(() => import('./pages/RequestLabs/patient_visit_lab_report')),
  },
  {
    path: '/RequestLabs/patient_visit_report',
    label: 'RequestLabs/patient_visit_report.php',
    sourcePath: 'templates/RequestLabs/patient_visit_report.php',
    Component: lazy(() => import('./pages/RequestLabs/patient_visit_report')),
  },
  {
    path: '/RequestLabs/pdf/patient_report',
    label: 'RequestLabs/pdf/patient_report.php',
    sourcePath: 'templates/RequestLabs/pdf/patient_report.php',
    Component: lazy(() => import('./pages/RequestLabs/pdf/patient_report')),
  },
  {
    path: '/RequestLabs/pdf/patient_visit_report',
    label: 'RequestLabs/pdf/patient_visit_report.php',
    sourcePath: 'templates/RequestLabs/pdf/patient_visit_report.php',
    Component: lazy(() => import('./pages/RequestLabs/pdf/patient_visit_report')),
  },
  {
    path: '/RequestLabs/report',
    label: 'RequestLabs/report.php',
    sourcePath: 'templates/RequestLabs/report.php',
    Component: lazy(() => import('./pages/RequestLabs/report')),
  },
  {
    path: '/RequestLabs/single_patient_visit_report',
    label: 'RequestLabs/single_patient_visit_report.php',
    sourcePath: 'templates/RequestLabs/single_patient_visit_report.php',
    Component: lazy(() => import('./pages/RequestLabs/single_patient_visit_report')),
  },
  {
    path: '/RequestLabs/specimen_tracker',
    label: 'RequestLabs/specimen_tracker.php',
    sourcePath: 'templates/RequestLabs/specimen_tracker.php',
    Component: lazy(() => import('./pages/RequestLabs/specimen_tracker')),
  },
  {
    path: '/RequestLabs/specimen_tracker_information',
    label: 'RequestLabs/specimen_tracker_information.php',
    sourcePath: 'templates/RequestLabs/specimen_tracker_information.php',
    Component: lazy(() => import('./pages/RequestLabs/specimen_tracker_information')),
  },
  {
    path: '/RequestLabs/view_request',
    label: 'RequestLabs/view_request.php',
    sourcePath: 'templates/RequestLabs/view_request.php',
    Component: lazy(() => import('./pages/RequestLabs/view_request')),
  },
  {
    path: '/RequestLabs/visit_request_lab_report',
    label: 'RequestLabs/visit_request_lab_report.php',
    sourcePath: 'templates/RequestLabs/visit_request_lab_report.php',
    Component: lazy(() => import('./pages/RequestLabs/visit_request_lab_report')),
  },
  {
    path: '/RequestMedications/all_patient_requested_medication_tp',
    label: 'RequestMedications/all_patient_requested_medication_tp.php',
    sourcePath: 'templates/RequestMedications/all_patient_requested_medication_tp.php',
    Component: lazy(() => import('./pages/RequestMedications/all_patient_requested_medication_tp')),
  },
  {
    path: '/RequestMedications/index',
    label: 'RequestMedications/index.php',
    sourcePath: 'templates/RequestMedications/index.php',
    Component: lazy(() => import('./pages/RequestMedications/index')),
  },
  {
    path: '/RequestMedications/other_items',
    label: 'RequestMedications/other_items.php',
    sourcePath: 'templates/RequestMedications/other_items.php',
    Component: lazy(() => import('./pages/RequestMedications/other_items')),
  },
  {
    path: '/RequestMedications/pdf/patient_report',
    label: 'RequestMedications/pdf/patient_report.php',
    sourcePath: 'templates/RequestMedications/pdf/patient_report.php',
    Component: lazy(() => import('./pages/RequestMedications/pdf/patient_report')),
  },
  {
    path: '/RequestMedications/report',
    label: 'RequestMedications/report.php',
    sourcePath: 'templates/RequestMedications/report.php',
    Component: lazy(() => import('./pages/RequestMedications/report')),
  },
  {
    path: '/RequestMedications/report_base',
    label: 'RequestMedications/report_base.php',
    sourcePath: 'templates/RequestMedications/report_base.php',
    Component: lazy(() => import('./pages/RequestMedications/report_base')),
  },
  {
    path: '/RequestMedications/view_infusion',
    label: 'RequestMedications/view_infusion.php',
    sourcePath: 'templates/RequestMedications/view_infusion.php',
    Component: lazy(() => import('./pages/RequestMedications/view_infusion')),
  },
  {
    path: '/RequestMedications/view_infusion_tp',
    label: 'RequestMedications/view_infusion_tp.php',
    sourcePath: 'templates/RequestMedications/view_infusion_tp.php',
    Component: lazy(() => import('./pages/RequestMedications/view_infusion_tp')),
  },
  {
    path: '/RequestMedications/view_medication',
    label: 'RequestMedications/view_medication.php',
    sourcePath: 'templates/RequestMedications/view_medication.php',
    Component: lazy(() => import('./pages/RequestMedications/view_medication')),
  },
  {
    path: '/RequestMedications/view_other_item_request',
    label: 'RequestMedications/view_other_item_request.php',
    sourcePath: 'templates/RequestMedications/view_other_item_request.php',
    Component: lazy(() => import('./pages/RequestMedications/view_other_item_request')),
  },
  {
    path: '/RequestMedications/view_prescription',
    label: 'RequestMedications/view_prescription.php',
    sourcePath: 'templates/RequestMedications/view_prescription.php',
    Component: lazy(() => import('./pages/RequestMedications/view_prescription')),
  },
  {
    path: '/RequestMedications/view_prescription_tp',
    label: 'RequestMedications/view_prescription_tp.php',
    sourcePath: 'templates/RequestMedications/view_prescription_tp.php',
    Component: lazy(() => import('./pages/RequestMedications/view_prescription_tp')),
  },
  {
    path: '/RequestMedications/view_request',
    label: 'RequestMedications/view_request.php',
    sourcePath: 'templates/RequestMedications/view_request.php',
    Component: lazy(() => import('./pages/RequestMedications/view_request')),
  },
  {
    path: '/RequestMedications/view_transfusion',
    label: 'RequestMedications/view_transfusion.php',
    sourcePath: 'templates/RequestMedications/view_transfusion.php',
    Component: lazy(() => import('./pages/RequestMedications/view_transfusion')),
  },
  {
    path: '/RequestPrescriptions/add',
    label: 'RequestPrescriptions/add.php',
    sourcePath: 'templates/RequestPrescriptions/add.php',
    Component: lazy(() => import('./pages/RequestPrescriptions/add')),
  },
  {
    path: '/RequestPrescriptions/edit',
    label: 'RequestPrescriptions/edit.php',
    sourcePath: 'templates/RequestPrescriptions/edit.php',
    Component: lazy(() => import('./pages/RequestPrescriptions/edit')),
  },
  {
    path: '/RequestPrescriptions/index',
    label: 'RequestPrescriptions/index.php',
    sourcePath: 'templates/RequestPrescriptions/index.php',
    Component: lazy(() => import('./pages/RequestPrescriptions/index')),
  },
  {
    path: '/RequestPrescriptions/view',
    label: 'RequestPrescriptions/view.php',
    sourcePath: 'templates/RequestPrescriptions/view.php',
    Component: lazy(() => import('./pages/RequestPrescriptions/view')),
  },
  {
    path: '/RequestRadiologies/index',
    label: 'RequestRadiologies/index.php',
    sourcePath: 'templates/RequestRadiologies/index.php',
    Component: lazy(() => import('./pages/RequestRadiologies/index')),
  },
  {
    path: '/RequestRadiologies/patient_visit_report',
    label: 'RequestRadiologies/patient_visit_report.php',
    sourcePath: 'templates/RequestRadiologies/patient_visit_report.php',
    Component: lazy(() => import('./pages/RequestRadiologies/patient_visit_report')),
  },
  {
    path: '/RequestRadiologies/radiology_scans_files',
    label: 'RequestRadiologies/radiology_scans_files.php',
    sourcePath: 'templates/RequestRadiologies/radiology_scans_files.php',
    Component: lazy(() => import('./pages/RequestRadiologies/radiology_scans_files')),
  },
  {
    path: '/RequestRadiologies/report',
    label: 'RequestRadiologies/report.php',
    sourcePath: 'templates/RequestRadiologies/report.php',
    Component: lazy(() => import('./pages/RequestRadiologies/report')),
  },
  {
    path: '/RequestRadiologies/scan_test_result',
    label: 'RequestRadiologies/scan_test_result.php',
    sourcePath: 'templates/RequestRadiologies/scan_test_result.php',
    Component: lazy(() => import('./pages/RequestRadiologies/scan_test_result')),
  },
  {
    path: '/RequestRadiologies/view_patient_scan_files',
    label: 'RequestRadiologies/view_patient_scan_files.php',
    sourcePath: 'templates/RequestRadiologies/view_patient_scan_files.php',
    Component: lazy(() => import('./pages/RequestRadiologies/view_patient_scan_files')),
  },
  {
    path: '/RequestRadiologies/view_process_scan',
    label: 'RequestRadiologies/view_process_scan.php',
    sourcePath: 'templates/RequestRadiologies/view_process_scan.php',
    Component: lazy(() => import('./pages/RequestRadiologies/view_process_scan')),
  },
  {
    path: '/RequestRadiologies/view_request',
    label: 'RequestRadiologies/view_request.php',
    sourcePath: 'templates/RequestRadiologies/view_request.php',
    Component: lazy(() => import('./pages/RequestRadiologies/view_request')),
  },
  {
    path: '/RequestRadiologies/view_scan_files',
    label: 'RequestRadiologies/view_scan_files.php',
    sourcePath: 'templates/RequestRadiologies/view_scan_files.php',
    Component: lazy(() => import('./pages/RequestRadiologies/view_scan_files')),
  },
  {
    path: '/RequestServices/index',
    label: 'RequestServices/index.php',
    sourcePath: 'templates/RequestServices/index.php',
    Component: lazy(() => import('./pages/RequestServices/index')),
  },
  {
    path: '/RequestServices/report',
    label: 'RequestServices/report.php',
    sourcePath: 'templates/RequestServices/report.php',
    Component: lazy(() => import('./pages/RequestServices/report')),
  },
  {
    path: '/RequestServices/view_request',
    label: 'RequestServices/view_request.php',
    sourcePath: 'templates/RequestServices/view_request.php',
    Component: lazy(() => import('./pages/RequestServices/view_request')),
  },
  {
    path: '/RequestSurgeries/edit_request_surgery',
    label: 'RequestSurgeries/edit_request_surgery.php',
    sourcePath: 'templates/RequestSurgeries/edit_request_surgery.php',
    Component: lazy(() => import('./pages/RequestSurgeries/edit_request_surgery')),
  },
  {
    path: '/RequestSurgeries/index',
    label: 'RequestSurgeries/index.php',
    sourcePath: 'templates/RequestSurgeries/index.php',
    Component: lazy(() => import('./pages/RequestSurgeries/index')),
  },
  {
    path: '/RequestSurgeries/report',
    label: 'RequestSurgeries/report.php',
    sourcePath: 'templates/RequestSurgeries/report.php',
    Component: lazy(() => import('./pages/RequestSurgeries/report')),
  },
  {
    path: '/RequestSurgeries/view',
    label: 'RequestSurgeries/view.php',
    sourcePath: 'templates/RequestSurgeries/view.php',
    Component: lazy(() => import('./pages/RequestSurgeries/view')),
  },
  {
    path: '/RequestSurgeries/view_request',
    label: 'RequestSurgeries/view_request.php',
    sourcePath: 'templates/RequestSurgeries/view_request.php',
    Component: lazy(() => import('./pages/RequestSurgeries/view_request')),
  },
  {
    path: '/RequestSurgeries/view_request_surgery',
    label: 'RequestSurgeries/view_request_surgery.php',
    sourcePath: 'templates/RequestSurgeries/view_request_surgery.php',
    Component: lazy(() => import('./pages/RequestSurgeries/view_request_surgery')),
  },
  {
    path: '/Roles/add_role',
    label: 'Roles/add_role.php',
    sourcePath: 'templates/Roles/add_role.php',
    Component: lazy(() => import('./pages/Roles/add_role')),
  },
  {
    path: '/Roles/edit_role',
    label: 'Roles/edit_role.php',
    sourcePath: 'templates/Roles/edit_role.php',
    Component: lazy(() => import('./pages/Roles/edit_role')),
  },
  {
    path: '/Roles/set_permissions',
    label: 'Roles/set_permissions.php',
    sourcePath: 'templates/Roles/set_permissions.php',
    Component: lazy(() => import('./pages/Roles/set_permissions')),
  },
  {
    path: '/Roles/view_role_details',
    label: 'Roles/view_role_details.php',
    sourcePath: 'templates/Roles/view_role_details.php',
    Component: lazy(() => import('./pages/Roles/view_role_details')),
  },
  {
    path: '/Roles/view_roles',
    label: 'Roles/view_roles.php',
    sourcePath: 'templates/Roles/view_roles.php',
    Component: lazy(() => import('./pages/Roles/view_roles')),
  },
  {
    path: '/Sessions/configure_session',
    label: 'Sessions/configure_session.php',
    sourcePath: 'templates/Sessions/configure_session.php',
    Component: lazy(() => import('./pages/Sessions/configure_session')),
  },
  {
    path: '/Sessions/create_session',
    label: 'Sessions/create_session.php',
    sourcePath: 'templates/Sessions/create_session.php',
    Component: lazy(() => import('./pages/Sessions/create_session')),
  },
  {
    path: '/Sessions/create_session_visit',
    label: 'Sessions/create_session_visit.php',
    sourcePath: 'templates/Sessions/create_session_visit.php',
    Component: lazy(() => import('./pages/Sessions/create_session_visit')),
  },
  {
    path: '/Sessions/create_voucher',
    label: 'Sessions/create_voucher.php',
    sourcePath: 'templates/Sessions/create_voucher.php',
    Component: lazy(() => import('./pages/Sessions/create_voucher')),
  },
  {
    path: '/Sessions/doctor_planner',
    label: 'Sessions/doctor_planner.php',
    sourcePath: 'templates/Sessions/doctor_planner.php',
    Component: lazy(() => import('./pages/Sessions/doctor_planner')),
  },
  {
    path: '/Sessions/index',
    label: 'Sessions/index.php',
    sourcePath: 'templates/Sessions/index.php',
    Component: lazy(() => import('./pages/Sessions/index')),
  },
  {
    path: '/Sessions/planner',
    label: 'Sessions/planner.php',
    sourcePath: 'templates/Sessions/planner.php',
    Component: lazy(() => import('./pages/Sessions/planner')),
  },
  {
    path: '/Sessions/planner_calendar',
    label: 'Sessions/planner_calendar.php',
    sourcePath: 'templates/Sessions/planner_calendar.php',
    Component: lazy(() => import('./pages/Sessions/planner_calendar')),
  },
  {
    path: '/Sessions/voucher_invoice_items',
    label: 'Sessions/voucher_invoice_items.php',
    sourcePath: 'templates/Sessions/voucher_invoice_items.php',
    Component: lazy(() => import('./pages/Sessions/voucher_invoice_items')),
  },
  {
    path: '/Sessions/voucher_payments',
    label: 'Sessions/voucher_payments.php',
    sourcePath: 'templates/Sessions/voucher_payments.php',
    Component: lazy(() => import('./pages/Sessions/voucher_payments')),
  },
  {
    path: '/Settings/add_setting',
    label: 'Settings/add_setting.php',
    sourcePath: 'templates/Settings/add_setting.php',
    Component: lazy(() => import('./pages/Settings/add_setting')),
  },
  {
    path: '/Settings/edit_discount',
    label: 'Settings/edit_discount.php',
    sourcePath: 'templates/Settings/edit_discount.php',
    Component: lazy(() => import('./pages/Settings/edit_discount')),
  },
  {
    path: '/Settings/edit_setting',
    label: 'Settings/edit_setting.php',
    sourcePath: 'templates/Settings/edit_setting.php',
    Component: lazy(() => import('./pages/Settings/edit_setting')),
  },
  {
    path: '/Settings/incall_queue',
    label: 'Settings/incall_queue.php',
    sourcePath: 'templates/Settings/incall_queue.php',
    Component: lazy(() => import('./pages/Settings/incall_queue')),
  },
  {
    path: '/Settings/index',
    label: 'Settings/index.php',
    sourcePath: 'templates/Settings/index.php',
    Component: lazy(() => import('./pages/Settings/index')),
  },
  {
    path: '/Settings/queue_manager',
    label: 'Settings/queue_manager.php',
    sourcePath: 'templates/Settings/queue_manager.php',
    Component: lazy(() => import('./pages/Settings/queue_manager')),
  },
  {
    path: '/Settings/view_settings',
    label: 'Settings/view_settings.php',
    sourcePath: 'templates/Settings/view_settings.php',
    Component: lazy(() => import('./pages/Settings/view_settings')),
  },
  {
    path: '/ShiftScheduler/edit_timeslot',
    label: 'ShiftScheduler/edit_timeslot.php',
    sourcePath: 'templates/ShiftScheduler/edit_timeslot.php',
    Component: lazy(() => import('./pages/ShiftScheduler/edit_timeslot')),
  },
  {
    path: '/ShiftScheduler/index',
    label: 'ShiftScheduler/index.php',
    sourcePath: 'templates/ShiftScheduler/index.php',
    Component: lazy(() => import('./pages/ShiftScheduler/index')),
  },
  {
    path: '/Sms/index',
    label: 'Sms/index.php',
    sourcePath: 'templates/Sms/index.php',
    Component: lazy(() => import('./pages/Sms/index')),
  },
  {
    path: '/Specialties/add_specialty',
    label: 'Specialties/add_specialty.php',
    sourcePath: 'templates/Specialties/add_specialty.php',
    Component: lazy(() => import('./pages/Specialties/add_specialty')),
  },
  {
    path: '/Specialties/edit_specialty',
    label: 'Specialties/edit_specialty.php',
    sourcePath: 'templates/Specialties/edit_specialty.php',
    Component: lazy(() => import('./pages/Specialties/edit_specialty')),
  },
  {
    path: '/Specialties/view_specialties',
    label: 'Specialties/view_specialties.php',
    sourcePath: 'templates/Specialties/view_specialties.php',
    Component: lazy(() => import('./pages/Specialties/view_specialties')),
  },
  {
    path: '/Users/change_password',
    label: 'Users/change_password.php',
    sourcePath: 'templates/Users/change_password.php',
    Component: lazy(() => import('./pages/Users/change_password')),
  },
  {
    path: '/Users/edit_user',
    label: 'Users/edit_user.php',
    sourcePath: 'templates/Users/edit_user.php',
    Component: lazy(() => import('./pages/Users/edit_user')),
  },
  {
    path: '/Users/login',
    label: 'Users/login.php',
    sourcePath: 'templates/Users/login.php',
    Component: lazy(() => import('./pages/Users/login')),
  },
  {
    path: '/Users/reset_password',
    label: 'Users/reset_password.php',
    sourcePath: 'templates/Users/reset_password.php',
    Component: lazy(() => import('./pages/Users/reset_password')),
  },
  {
    path: '/Users/update_profile',
    label: 'Users/update_profile.php',
    sourcePath: 'templates/Users/update_profile.php',
    Component: lazy(() => import('./pages/Users/update_profile')),
  },
  {
    path: '/Users/update_profile_copy',
    label: 'Users/update_profile_copy.php',
    sourcePath: 'templates/Users/update_profile_copy.php',
    Component: lazy(() => import('./pages/Users/update_profile_copy')),
  },
  {
    path: '/Users/view_user_details',
    label: 'Users/view_user_details.php',
    sourcePath: 'templates/Users/view_user_details.php',
    Component: lazy(() => import('./pages/Users/view_user_details')),
  },
  {
    path: '/VisitsReport/index',
    label: 'VisitsReport/index.php',
    sourcePath: 'templates/VisitsReport/index.php',
    Component: lazy(() => import('./pages/VisitsReport/index')),
  },
  {
    path: '/VspProcurement/edit',
    label: 'VspProcurement/edit.php',
    sourcePath: 'templates/VspProcurement/edit.php',
    Component: lazy(() => import('./pages/VspProcurement/edit')),
  },
  {
    path: '/VspProcurement/index',
    label: 'VspProcurement/index.php',
    sourcePath: 'templates/VspProcurement/index.php',
    Component: lazy(() => import('./pages/VspProcurement/index')),
  },
  {
    path: '/VspProcurement/requestapproval',
    label: 'VspProcurement/requestapproval.php',
    sourcePath: 'templates/VspProcurement/requestapproval.php',
    Component: lazy(() => import('./pages/VspProcurement/requestapproval')),
  },
  {
    path: '/VspProcurement/vsp_view',
    label: 'VspProcurement/vsp_view.php',
    sourcePath: 'templates/VspProcurement/vsp_view.php',
    Component: lazy(() => import('./pages/VspProcurement/vsp_view')),
  },
] as const;
